# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCloudSearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'CR', b'CR'), (b'CPB', b'CPB'), (b'TRR', b'TRR'), (b'OCIR', b'OCIR'), (b'OBR', b'OBR'), (b'AR', b'AR'), (b'CHI-R', b'CHI-R'), (b'incident/offense', b'Incident/Offense Report')], max_length=20)),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCrawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('num_documents', models.IntegerField()),
            ],
        ),
    ]
