# Generated by Django 2.1.3 on 2018-11-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_cloud', '0002_add_documentcrawler_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcloudsearchquery',
            name='type',
            field=models.CharField(choices=[('CR', 'CR'), ('CPB', 'CPB'), ('TRR', 'TRR'), ('OCIR', 'OCIR'), ('OBR', 'OBR'), ('AR', 'AR'), ('CHI-R', 'CHI-R'), ('incident/offense', 'Incident/Offense Report')], max_length=20),
        ),
    ]
