# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 03:21
from __future__ import unicode_literals

from django.db import migrations

from data.constants import AttachmentSourceType


def set_source_type(apps, schema_editor):
    DocumentCrawler = apps.get_model('document_cloud', 'DocumentCrawler')
    DocumentCrawler.objects.all().update(source_type=AttachmentSourceType.DOCUMENTCLOUD)


class Migration(migrations.Migration):
    dependencies = [
        ('document_cloud', '0003_documentcrawler_source_type'),
    ]

    operations = [
        migrations.RunPython(
            set_source_type,
            reverse_code=migrations.RunPython.noop,
            elidable=True),
    ]
