# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_cloud', '0004_documentcrawler_correct_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcrawler',
            name='source_type',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
