# Generated by Django 2.1.3 on 2018-11-30 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_cloud', '0005_documentcrawler_source_type_no_defaut_value'),
        ('document_cloud', '0003_alter_documentcloudsearchquery_type'),
    ]

    operations = [
    ]
