# Generated by Django 2.1.3 on 2018-12-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_cloud', '0006_merge_20181129_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentcrawler',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
