# Generated by Django 2.1.3 on 2018-12-14 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('document_cloud', '0007_rename_timestamp_to_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcloudsearchquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentcloudsearchquery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documentcrawler',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
