# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 03:21
from __future__ import unicode_literals

from django.db import migrations


def set_source_type(apps, schema_editor):
    DocumentCrawler = apps.get_model('document_cloud', 'DocumentCrawler')
    DocumentCrawler.objects.filter(source_type='COPA').update(source_type='PORTAL_COPA')


class Migration(migrations.Migration):
    dependencies = [
        ('document_cloud', '0008_add_created_at_and_updated_at_columns'),
    ]

    operations = [
        migrations.RunPython(set_source_type)
    ]
