# Generated by Django 2.1.3 on 2019-02-25 07:52

from django.db import migrations, models
from django.db.models import Subquery, OuterRef, Count


class Migration(migrations.Migration):
    def set_status(apps, schema_editor):
        DocumentCrawler = apps.get_model('document_cloud', 'DocumentCrawler')
        DocumentCrawler.objects.update(status='Success')

    def set_num_successful_run(apps, schema_editor):
        DocumentCrawler = apps.get_model('document_cloud', 'DocumentCrawler')
        DocumentCrawler.objects.update(
            num_successful_run=Subquery(
                DocumentCrawler.objects.filter(
                    source_type=OuterRef('source_type'),
                    created_at__lte=OuterRef('created_at'),
                    status='Success'
                ).values('source_type').annotate(
                    count=Count('id')
                ).values('count')[:1]
            )
        )

    dependencies = [
        ('document_cloud', '0009_document_crawler_update_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcrawler',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentcrawler',
            name='num_successful_run',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(
            set_status,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            set_num_successful_run,
            reverse_code=migrations.RunPython.noop,
        )
    ]
