# Generated by Django 2.1.3 on 2019-02-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_cloud', '0010_documentcrawler_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcrawler',
            name='log_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
