# Generated by Django 2.1.11 on 2019-11-25 08:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_cloud', '0011_documentcrawler_log_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcloudsearchquery',
            name='type',
        ),
        migrations.AddField(
            model_name='documentcloudsearchquery',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CR', 'CR'), ('CPB', 'CPB'), ('TRR', 'TRR'), ('OCIR', 'OCIR'), ('OBR', 'OBR'), ('AR', 'AR'), ('CHI-R', 'CHI-R'), ('incident/offense', 'Incident/Offense Report')], max_length=20), default=list, size=None),
        ),
    ]
