# Generated by Django 2.2.9 on 2020-01-10 04:35

from django.db import migrations, models
import utils.models.choice_array_field


class Migration(migrations.Migration):

    dependencies = [
        ('document_cloud', '0012_change_document_cloud_search_query_type_to_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcloudsearchquery',
            name='types',
            field=utils.models.choice_array_field.ChoiceArrayField(base_field=models.CharField(choices=[('CR', 'CR'), ('CPB', 'CPB'), ('TRR', 'TRR'), ('DOCUMENT', 'DOCUMENT'), ('OCIR', 'OCIR'), ('OBR', 'OBR'), ('AR', 'AR'), ('CHI-R', 'CHI-R'), ('incident/offense', 'Incident/Offense Report')], max_length=20), default=list, size=None),
        ),
    ]
