# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspaper',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='newspaper',
            name='canonical_url',
        ),
        migrations.AddField(
            model_name='newspaper',
            name='short_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storypage',
            name='canonical_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='storypage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
