# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_modifications_to_newspaper_and_storypage'),
    ]

    operations = [
    ]
