# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
