# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-31 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields

from tqdm import tqdm


def copy_data_from_storypage_to_story(apps, schema_editor):
    Story = apps.get_model('story', 'Story')
    StoryPage = apps.get_model('story', 'StoryPage')
    for story_page in tqdm(StoryPage.objects.all(), desc='Create stories'):
        Story.objects.create(
            title=story_page.title,
            newspaper=story_page.newspaper,
            canonical_url=story_page.canonical_url,
            post_date=story_page.post_date,
            image=story_page.image,
            body=story_page.body)


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_storypage_featured_story'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('wagtailredirects', '0005_capitalizeverbose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_url', models.URLField(null=True)),
                ('post_date', models.DateField(null=True)),
                ('body', wagtail.wagtailcore.fields.StreamField([(b'paragraph', wagtail.wagtailcore.blocks.TextBlock())])),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('newspaper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='story.Newspaper')),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            options={'verbose_name_plural': 'stories'},
        ),
        migrations.RunPython(copy_data_from_storypage_to_story),
        migrations.RemoveField(
            model_name='storypage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='storypage',
            name='newspaper',
        ),
        migrations.RemoveField(
            model_name='storypage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='StoryPage',
        ),
    ]
