# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('story', '0005_reportingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_url', models.URLField(null=True)),
                ('post_date', models.DateField(null=True)),
                ('body', wagtail.wagtailcore.fields.StreamField([(b'paragraph', wagtail.wagtailcore.blocks.TextBlock())])),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('newspaper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='story.Newspaper')),
            ],
        ),
        migrations.AddField(
            model_name='reportingpage',
            name='reports',
            field=models.ManyToManyField(null=True, to='story.Story'),
        ),
    ]
