# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_auto_20160829_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reportingpage',
            name='reports',
            field=models.ManyToManyField(to='story.Story'),
        ),
    ]
