# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 03:00
from __future__ import unicode_literals

from django.db import migrations

from tqdm import tqdm


def copy_data_from_storypage_to_story(apps, schema_editor):
    Story = apps.get_model('story', 'Story')
    StoryPage = apps.get_model('story', 'StoryPage')
    for story_page in tqdm(StoryPage.objects.all(), desc='Create stories'):
        Story.objects.create(
            title=story_page.title,
            newspaper=story_page.newspaper,
            canonical_url=story_page.canonical_url,
            post_date=story_page.post_date,
            image=story_page.image,
            body=story_page.body)


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_auto_20160829_2159'),
    ]

    operations = [
        migrations.RunPython(copy_data_from_storypage_to_story),
    ]
