# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_remove_auto_now_add_from_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
        migrations.RemoveField(
            model_name='story',
            name='newspaper',
        ),
        migrations.DeleteModel(
            name='Newspaper',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
