# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_remove_newspaper_story_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storypage',
            old_name='publication_short_url',
            new_name='publication_short_name',
        ),
    ]
