# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('landing_page', '0005_auto_20160829_2232'),
        ('story', '0008_migrate_data_from_storypage_to_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportingpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='reportingpage',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='storypage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='storypage',
            name='newspaper',
        ),
        migrations.RemoveField(
            model_name='storypage',
            name='page_ptr',
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'stories'},
        ),
        migrations.DeleteModel(
            name='ReportingPage',
        ),
        migrations.DeleteModel(
            name='StoryPage',
        ),
    ]
