# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-13 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('story', '0009_auto_20160918_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveragepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='storypage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='storypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='storypage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='storypagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='storypagetag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='CoveragePage',
        ),
        migrations.DeleteModel(
            name='StoryPage',
        ),
        migrations.DeleteModel(
            name='StoryPageTag',
        ),
    ]
