# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 08:03
from __future__ import unicode_literals

from django.core.management import BaseCommand
from django.contrib.contenttypes.models import ContentType

from tqdm import tqdm
from wagtail.wagtailcore.models import Page

from faq.models import FAQsPage, FAQPage, FAQ


class Command(BaseCommand):
    def handle(self, *args, **options):
        root_page = Page.objects.get(pk=1)
        faqs_page = root_page.add_child(
            instance=FAQsPage(
                title='FAQ', slug='faq', content_type=ContentType.objects.get_for_model(FAQsPage)
            ))

        for faq in tqdm(FAQ.objects.all(), desc='Create faqs'):
            faqs_page.add_child(instance=FAQPage(
                content_type=ContentType.objects.get_for_model(FAQPage),
                title=faq.title,
                body=faq.body))
