# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-09 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[[b'single_officer', b'Single Officer'], [b'coaccused_pair', b'Coaccused Pair'], [b'not_found', b'Not Found']], max_length=20)),
                ('syntax', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TwitterBotResponseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.TextField()),
                ('entity_url', models.URLField(blank=True)),
                ('tweet_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tweet_url', models.URLField(blank=True)),
                ('incoming_tweet_username', models.CharField(max_length=15)),
                ('incoming_tweet_url', models.URLField()),
                ('incoming_tweet_content', models.TextField()),
                ('original_tweet_username', models.CharField(max_length=15)),
                ('original_tweet_url', models.URLField()),
                ('original_tweet_content', models.TextField()),
                ('status', models.CharField(choices=[(b'PENDING', b'Pending'), (b'SENT', b'Sent')], default=b'PENDING', max_length=10)),
            ],
        ),
    ]
