# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-02 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[[b'single_officer', b'Single Officer'], [b'coaccused_pair', b'Coaccused Pair'], [b'not_found', b'Not Found']], max_length=20)),
                ('syntax', models.TextField()),
            ],
        ),
    ]
