# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-04 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterBotResponseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.TextField()),
                ('entity_url', models.URLField()),
                ('tweet_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tweet_url', models.URLField()),
                ('incoming_tweet_username', models.CharField(max_length=50)),
                ('incoming_tweet_url', models.URLField()),
                ('incoming_tweet_content', models.TextField()),
                ('originating_tweet_username', models.CharField(blank=True, max_length=50)),
                ('originating_tweet_url', models.URLField(blank=True)),
                ('originating_tweet_content', models.TextField(blank=True)),
            ],
        ),
    ]
