# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 01:13
from __future__ import unicode_literals

from django.db import migrations


def create_initial_response_template_data(apps, schema_editor):
    ResponseTemplate = apps.get_model('twitterbot', 'ResponseTemplate')
    ResponseTemplate.objects.create(
        response_type='single_officer',
        syntax=(
            "@{{user_name}} {% if officer.rank %}{{officer.rank}} {% endif %}{{officer.full_name}}"
            "{% if officer.current_badge %} ({{officer.current_badge}}){% endif %} has {{officer.allegation_count}} "
            "complaint{{officer.allegation_count|pluralize}}, and has {% if officer.discipline_count == 0 %}not "
            "been disciplined{% else %}been disciplined {{officer.discipline_count}} "
            "time{{officer.discipline_count|pluralize}}{% endif %}."))
    ResponseTemplate.objects.create(
        response_type='coaccused_pair',
        syntax=(
            '@{{user_name}} {{officer1.full_name}} and {{officer2.full_name}} '
            'were co-accused in {{coaccused}} case{{coaccused|pluralize}}'))
    ResponseTemplate.objects.create(
        response_type='not_found',
        syntax=(
            "Sorry, @{{user_name}}, the bot didn't recognize an officer name. "
            "Try again by tweeting the name to us?"))


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_response_template_data),
    ]
