# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-04 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0002_twitterbotresponselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterbotresponselog',
            name='incoming_tweet_username',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='twitterbotresponselog',
            name='originating_tweet_username',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
