# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-04 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0003_auto_20170803_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterbotresponselog',
            old_name='originating_tweet_content',
            new_name='original_tweet_content',
        ),
        migrations.RenameField(
            model_name='twitterbotresponselog',
            old_name='originating_tweet_url',
            new_name='original_tweet_url',
        ),
        migrations.RenameField(
            model_name='twitterbotresponselog',
            old_name='originating_tweet_username',
            new_name='original_tweet_username',
        ),
    ]
