# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0003_auto_20171019_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterBotVisitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_path', models.CharField(max_length=255)),
                ('response_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitterbot.TwitterBotResponseLog')),
            ],
        ),
    ]
