# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-08 03:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0004_twitterbotvisitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterbotresponselog',
            name='original_event_object',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
