#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $APPLICATION_DB_USER;
    ALTER USER $APPLICATION_DB_USER WITH ENCRYPTED PASSWORD '$APPLICATION_DB_PASSWORD';
    CREATE DATABASE $APPLICATION_DB;
    GRANT ALL PRIVILEGES ON DATABASE $APPLICATION_DB TO $APPLICATION_DB_USER;
EOSQL
