FORMAT: 1A
HOST: http://cpdp.apiblueprint.org/

# CPDP

CPDP is a simple API serving the CPDP website version 2 (not the same as api version) now live at https://beta.cpdp.co. It includes two main portions: CMS and data tool.

**Conventions**:

- Property name is in snake case: `field_name` instead of `fieldName`

## CMS Page [/cms-pages/{page_id}/]

+ Parameters
    + page_id (string) - ID of the Page that look like a slug

### Get CMS page content [GET]

**Properties**:

- `fields` is an array of fields. Each fields has `name`, `type` and `value`. `value` is an opaque object that should be only of interest to whatever module that deal with it directly. As such it's content might violate some of conventions followed elsewhere such as having property name be in snake case.

+ Response 200 (application/json)

        {
            "fields": [
                {
                    "name": "reports",
                    "type": "randomized_list",
                    "value": [
                        {
                            "id": 1,
                            "fields": [
                                {
                                    "name": "title",
                                    "type": "plain_text",
                                    "value": {
                                        "blocks": [
                                            {
                                                "data": {},
                                                "depth": 0,
                                                "entityRanges": [],
                                                "inlineStyleRanges": [],
                                                "key": "5gia1",
                                                "text": "Commentary: Chicago's police crisis",
                                                "type": "unstyled"
                                            }
                                        ],
                                        "entityMap": {}
                                    }
                                },
                                {
                                    "name": "excerpt",
                                    "type": "multiline_text",
                                    "value": {
                                        "blocks": [
                                            {
                                                "data": {},
                                                "depth": 0,
                                                "entityRanges": [],
                                                "inlineStyleRanges": [],
                                                "key": "a4b9s",
                                                "text": "The “few bad apples” theory of police violence posits that a small portion of the police force is ill-intentioned or inclined to misconduct or violence, while the majority of officers are good cops. Until recently, this theory was difficult for civilians to investigate, but department data on complaints against officers obtained through a legal challenge shows that police misconduct in Chicago is overwhelmingly the product of a small fraction of officers and that it may be possible to identify those officers and reduce misconduct.",
                                                "type": "unstyled"
                                            },
                                            {
                                                "data": {},
                                                "depth": 0,
                                                "entityRanges": [],
                                                "inlineStyleRanges": [],
                                                "key": "a4b9z",
                                                "text": "This far-reaching data set, a product of the nonprofit Invisible Institute’s Citizens Police Data Project, comprehensively covers nearly five years of complaints against Chicago police officers. Each of the 28,588 records in the database offers a detailed account of the incident, including information on the accused officer, the complainant, the type of alleged misconduct, and whether the complaint was found legitimate by an internal investigation.",
                                                "type": "unstyled"
                                            }
                                        ],
                                        "entityMap": {}
                                    }
                                },
                                {
                                    "name": "publication",
                                    "type": "string",
                                    "value": "New York Times"
                                },
                                {
                                    "name": "publish_date",
                                    "type": "date",
                                    "value": "2016-09-23"
                                },
                                {
                                    "name": "author",
                                    "type": "string",
                                    "value": "Edgar Sterling"
                                }
                            ]
                        }
                    ]
                },
                {
                    "name": "reporting_header",
                    "type": "plain_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "5kif1",
                                "text": "Recent Reports",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "reporting_randomizer",
                    "type": "randomizer",
                    "value": {
                        "poolSize": "10",
                        "selectedStrategyId": "1",
                        "strategies": [
                            {
                                "id": "1",
                                "name": "Last entries"
                            },
                            {
                                "id": "2",
                                "name": "Last days"
                            }
                        ]
                    }
                },
                {
                    "name": "faq_header",
                    "type": "plain_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "5kia1",
                                "text": "FAQ",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "faq_randomizer",
                    "type": "randomizer",
                    "value": {
                        "poolSize": "10",
                        "selectedStrategyId": "1",
                        "strategies": [
                            {
                                "id": "1",
                                "name": "Last entries"
                            },
                            {
                                "id": "2",
                                "name": "Last days"
                            }
                        ]
                    }
                },
                {
                    "name": "vftg_date",
                    "type": "date",
                    "value": "2016-10-07"
                },
                {
                    "name": "vftg_link",
                    "type": "link",
                    "value": "https://google.com"
                },
                {
                    "name": "vftg_content",
                    "type": "plain_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "5gia1",
                                "text": "Real Independence for Police Oversight Agencies",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "collaborate_header",
                    "type": "plain_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "5gia1",
                                "text": "Collaborate With Us.",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "collaborate_content",
                    "type": "multiline_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a4b9s",
                                "text": "We are collecting and publishing information that sheds light on police misconduct.",
                                "type": "unstyled"
                            },
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a4b9z",
                                "text": "If you have documents or datasets you would like to publish, please email us, or learn more.",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "about_header",
                    "type": "plain_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a89s0",
                                "text": "About",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "about_content",
                    "type": "multiline_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a9sn8",
                                "text": "The Citizens Police Data Project houses police disciplinary information obtained from the City of Chicago..",
                                "type": "unstyled"
                            },
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a9sn5",
                                "text": "The information and stories we have collected here are intended as a resource for public oversight. Our aim is to create a new model of accountability between officers and citizens.",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                }
            ]
        }

### Partial update CMS page content [PATCH]

This api require an api access token set in `Authorization` header. To get an api access token, use **Sign In** api.

+ Request (application/json)

    + Headers

            Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b

    + Body

            {
                "fields": [
                    {
                        "name": "collaborate_header",
                        "type": "plain_text",
                        "value": {
                            "blocks": [
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "5gia1",
                                    "text": "Collaborate With Us.",
                                    "type": "unstyled"
                                }
                            ],
                            "entityMap": {}
                        }
                    },
                    {
                        "name": "collaborate_content",
                        "type": "multiline_text",
                        "value": {
                            "blocks": [
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "a4b9s",
                                    "text": "We are collecting and publishing information that sheds light on police misconduct.",
                                    "type": "unstyled"
                                },
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "a4b9z",
                                    "text": "If you have documents or datasets you would like to publish, please email us, or learn more.",
                                    "type": "unstyled"
                                }
                            ],
                            "entityMap": {}
                        }
                    }
                ]
            }

+ Response 200 (application/json)

            {
                "fields": [
                {
                    "name": "reporting_header",
                    "type": "plain_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "5kif1",
                                "text": "Recent Reports",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "reporting_randomizer",
                    "type": "randomizer",
                    "value": {
                        "poolSize": "10",
                        "selectedStrategyId": "1",
                        "strategies": [
                            {
                                "id": "1",
                                "name": "Last entries"
                            },
                            {
                                "id": "2",
                                "name": "Last days"
                            }
                        ]
                    }
                },
                {
                    "name": "faq_header",
                    "type": "plain_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "5kia1",
                                "text": "FAQ",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "faq_randomizer",
                    "type": "randomizer",
                    "value": {
                        "poolSize": "10",
                        "selectedStrategyId": "1",
                        "strategies": [
                            {
                                "id": "1",
                                "name": "Last entries"
                            },
                            {
                                "id": "2",
                                "name": "Last days"
                            }
                        ]
                    }
                },
                {
                    "name": "vftg_date",
                    "type": "date",
                    "value": "2016-10-07"
                },
                {
                    "name": "vftg_link",
                    "type": "link",
                    "value": "https://google.com"
                },
                {
                    "name": "vftg_content",
                    "type": "plain_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "5gia1",
                                "text": "Real Independence for Police Oversight Agencies",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "collaborate_header",
                    "type": "plain_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "5gia1",
                                "text": "Collaborate With Us.",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "collaborate_content",
                    "type": "multiline_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a4b9s",
                                "text": "We are collecting and publishing information that sheds light on police misconduct.",
                                "type": "unstyled"
                            },
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a4b9z",
                                "text": "If you have documents or datasets you would like to publish, please email us, or learn more.",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "about_header",
                    "type": "plain_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a89s0",
                                "text": "About",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "about_content",
                    "type": "multiline_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a9sn8",
                                "text": "The Citizens Police Data Project houses police disciplinary information obtained from the City of Chicago..",
                                "type": "unstyled"
                            },
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a9sn5",
                                "text": "The information and stories we have collected here are intended as a resource for public oversight. Our aim is to create a new model of accountability between officers and citizens.",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                }
            ]
        }

+ Request (application/json)

        {
            "fields": [
                {
                    "name": "collaborate_header",
                    "type": "plain_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "5gia1",
                                "text": "Collaborate With Us.",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                }
            ]
        }

+ Response 401 (application/json)

    + Headers

            WWW-Authenticate: Token

## Sign In [/users/sign-in/]

### Sign in and get an api access token [POST]

+ Request (application/json)

        {
            "username": "admin",
            "password": "admin@123"
        }

+ Response 200 (application/json)

        {
            "apiAccessToken": "9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b"
        }

+ Request (application/json)

        {
            "username": "incorrectname",
            "password": "password"
        }

+ Response 400 (application/json)

        {
            "message": "Sorry, you’ve entered an incorrect name."
        }

+ Request (application/json)

        {
            "username": "admin",
            "password": "incorrect"
        }

+ Response 400 (application/json)

        {
            "message": "You’ve entered an incorrect password."
        }

## Forgot password [/users/forgot-password/]

### Forgot password [POST]

+ Request (application/json)

        {
            "email": "admin@domain.com"
        }

+ Response 200 (application/json)

        {
            "message": "Please check your email for a password reset link."
        }

+ Request (application/json)

        {
            "email": "unregistered@email.co"
        }

+ Response 400 (application/json)

        {
            "message": "Sorry, there’s no account registered with this email address."
        }

## Reports list [/reports/]

### Get reports [GET]

+ Response 200 (application/json)

        {
            "results": [
                {
                    "id": 1,
                    "fields": [
                        {
                            "name": "title",
                            "type": "plain_text",
                            "value": {
                                "blocks": [
                                    {
                                        "data": {},
                                        "depth": 0,
                                        "entityRanges": [],
                                        "inlineStyleRanges": [],
                                        "key": "5gia1",
                                        "text": "Commentary: Chicago's police crisis fall on all of us",
                                        "type": "unstyled"
                                    }
                                ],
                                "entityMap": {}
                            }
                        },
                        {
                            "name": "excerpt",
                            "type": "multiline_text",
                            "value": {
                                "blocks": [
                                    {
                                        "data": {},
                                        "depth": 0,
                                        "entityRanges": [],
                                        "inlineStyleRanges": [],
                                        "key": "a4b9s",
                                        "text": "The “few bad apples” theory of police violence posits that a small portion of the police force is ill-intentioned or inclined to misconduct or violence, while the majority of officers are good cops. Until recently, this theory was difficult for civilians to investigate, but department data on complaints against officers obtained through a legal challenge shows that police misconduct in Chicago is overwhelmingly the product of a small fraction of officers and that it may be possible to identify those officers and reduce misconduct.",
                                        "type": "unstyled"
                                    },
                                    {
                                        "data": {},
                                        "depth": 0,
                                        "entityRanges": [],
                                        "inlineStyleRanges": [],
                                        "key": "a4b9z",
                                        "text": "This far-reaching data set, a product of the nonprofit Invisible Institute’s Citizens Police Data Project, comprehensively covers nearly five years of complaints against Chicago police officers. Each of the 28,588 records in the database offers a detailed account of the incident, including information on the accused officer, the complainant, the type of alleged misconduct, and whether the complaint was found legitimate by an internal investigation.",
                                        "type": "unstyled"
                                    }
                                ],
                                "entityMap": {}
                            }
                        },
                        {
                            "name": "publication",
                            "type": "string",
                            "value": "New York Times"
                        },
                        {
                            "name": "publish_date",
                            "type": "date",
                            "value": "2016-09-23"
                        },
                        {
                            "name": "author",
                            "type": "string",
                            "value": "Edgar Sterling"
                        }
                    ]
                }
            ]
        }

## Report Detail [/reports/{report_id}/]

+ Parameters
    + report_id (number) - number ID of the report

### Retrieve report [GET]

+ Response 200 (application/json)

            {
                "id": 1,
                "fields": [
                    {
                        "name": "title",
                        "type": "plain_text",
                        "value": {
                            "blocks": [
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "5gia1",
                                    "text": "Commentary: Chicago's police crisis",
                                    "type": "unstyled"
                                }
                            ],
                            "entityMap": {}
                        }
                    },
                    {
                        "name": "excerpt",
                        "type": "multiline_text",
                        "value": {
                            "blocks": [
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "a4b9s",
                                    "text": "The “few bad apples” theory of police violence posits that a small portion of the police force is ill-intentioned or inclined to misconduct or violence, while the majority of officers are good cops. Until recently, this theory was difficult for civilians to investigate, but department data on complaints against officers obtained through a legal challenge shows that police misconduct in Chicago is overwhelmingly the product of a small fraction of officers and that it may be possible to identify those officers and reduce misconduct.",
                                    "type": "unstyled"
                                },
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "a4b9z",
                                    "text": "This far-reaching data set, a product of the nonprofit Invisible Institute’s Citizens Police Data Project, comprehensively covers nearly five years of complaints against Chicago police officers. Each of the 28,588 records in the database offers a detailed account of the incident, including information on the accused officer, the complainant, the type of alleged misconduct, and whether the complaint was found legitimate by an internal investigation.",
                                    "type": "unstyled"
                                }
                            ],
                            "entityMap": {}
                        }
                    },
                    {
                        "name": "publication",
                        "type": "string",
                        "value": "New York Times"
                    },
                    {
                        "name": "publish_date",
                        "type": "date",
                        "value": "2016-09-23"
                    },
                    {
                        "name": "author",
                        "type": "string",
                        "value": "Edgar Sterling"
                    },
                    {
                        "name": "officers",
                        "type": "officers_list",
                        "value": [
                            {
                                "id": 123,
                                "full_name": "Edgar Davis",
                                "allegation_count": 14,
                                "v1_url": "http://cpdb.co/officer/edgar/123",
                                "gender": "Male",
                                "race": "White"
                            }
                        ]
                    }
                ]

        }

### Partial Update report [PATCH]

This api require an api access token set in `Authorization` header. To get an api access token, use **Sign In** api.

+ Request (application/json)

    + Headers

            Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b

    + Body

            {
                "fields": [
                    {
                        "name": "title",
                        "type": "plain_text",
                        "value": {
                            "blocks": [
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "5gia1",
                                    "text": "Commentary: Chicago's police crisis fall on all of us",
                                    "type": "unstyled"
                                }
                            ],
                            "entityMap": {}
                        }
                    },
                    {
                        "name": "excerpt",
                        "type": "multiline_text",
                        "value": {
                            "blocks": [
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "a4b9s",
                                    "text": "The “few bad apples” theory of police violence posits that a small portion of the police force is ill-intentioned or inclined to misconduct or violence, while the majority of officers are good cops. Until recently, this theory was difficult for civilians to investigate, but department data on complaints against officers obtained through a legal challenge shows that police misconduct in Chicago is overwhelmingly the product of a small fraction of officers and that it may be possible to identify those officers and reduce misconduct.",
                                    "type": "unstyled"
                                },
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "a4b9z",
                                    "text": "This far-reaching data set, a product of the nonprofit Invisible Institute’s Citizens Police Data Project, comprehensively covers nearly five years of complaints against Chicago police officers. Each of the 28,588 records in the database offers a detailed account of the incident, including information on the accused officer, the complainant, the type of alleged misconduct, and whether the complaint was found legitimate by an internal investigation.",
                                    "type": "unstyled"
                                }
                            ],
                            "entityMap": {}
                        }
                    }
                ]
            }

+ Response 200 (application/json)

            {
                "id": 1,
                "fields": [
                    {
                        "name": "title",
                        "type": "plain_text",
                        "value": {
                            "blocks": [
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "5gia1",
                                    "text": "Commentary: Chicago's police crisis",
                                    "type": "unstyled"
                                }
                            ],
                            "entityMap": {}
                        }
                    },
                    {
                        "name": "excerpt",
                        "type": "multiline_text",
                        "value": {
                            "blocks": [
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "a4b9s",
                                    "text": "The “few bad apples” theory of police violence posits that a small portion of the police force is ill-intentioned or inclined to misconduct or violence, while the majority of officers are good cops. Until recently, this theory was difficult for civilians to investigate, but department data on complaints against officers obtained through a legal challenge shows that police misconduct in Chicago is overwhelmingly the product of a small fraction of officers and that it may be possible to identify those officers and reduce misconduct.",
                                    "type": "unstyled"
                                },
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "a4b9z",
                                    "text": "This far-reaching data set, a product of the nonprofit Invisible Institute’s Citizens Police Data Project, comprehensively covers nearly five years of complaints against Chicago police officers. Each of the 28,588 records in the database offers a detailed account of the incident, including information on the accused officer, the complainant, the type of alleged misconduct, and whether the complaint was found legitimate by an internal investigation.",
                                    "type": "unstyled"
                                }
                            ],
                            "entityMap": {}
                        }
                    },
                    {
                        "name": "publication",
                        "type": "string",
                        "value": "New York Times"
                    },
                    {
                        "name": "publish_date",
                        "type": "date",
                        "value": "2016-09-23"
                    },
                    {
                        "name": "author",
                        "type": "string",
                        "value": "Edgar Sterling"
                    },
                    {
                        "name": "officers",
                        "type": "officers_list",
                        "value": [
                            {
                                "id": 123,
                                "full_name": "Edgar Davis",
                                "allegation_count": 14,
                                "v1_url": "http://cpdb.co/officer/edgar/123",
                                "gender": "Male",
                                "race": "White"
                            }
                        ]
                    }
                ]

        }

## FAQ list [/faqs/]

### Create faq [POST]
+ Request (application/json)

    + Headers

            Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b

    + Body

            {
                "fields": [
                    {
                        "name": "question",
                        "type": "plain_text",
                        "value": {
                            "entityMap": {},
                            "blocks": [
                                {
                                    "key": "6490e",
                                    "text": "Question A",
                                    "type": "unstyled",
                                    "depth": 0,
                                    "inlineStyleRanges": [],
                                    "entityRanges": [],
                                    "data": {}
                                }
                            ]
                        }
                    },
                    {
                        "name": "answer",
                        "type": "multiline_text",
                        "value": {
                            "entityMap": {},
                            "blocks": [
                                {
                                    "key": "eog14",
                                    "text": "Answer A",
                                    "type": "unstyled",
                                    "depth": 0,
                                    "inlineStyleRanges": [],
                                    "entityRanges": [],
                                    "data": {}
                                }
                            ]
                        }
                    }
                ]
            }

+ Response 201 (application/json)

        {
            "fields": [
                {
                    "type": "rich_text",
                    "name": "question",
                    "value": {
                        "entityMap": {},
                        "blocks": [
                            {
                                "text": "Question A",
                                "entityRanges": [],
                                "depth": 0,
                                "data": {},
                                "key": "6490e",
                                "inlineStyleRanges": [],
                                "type": "unstyled"
                            }
                        ]
                    }
                },
                {
                    "type": "rich_text",
                    "name": "answer",
                    "value": {
                        "entityMap": {},
                        "blocks": [
                            {
                                "text": "Answer A",
                                "entityRanges": [],
                                "depth": 0,
                                "data": {},
                                "key": "eog14",
                                "inlineStyleRanges": [],
                                "type": "unstyled"
                            }
                        ]
                    }
                }
            ],
            "meta": {
                "order": 1,
                "starred": false
            }
            "id": 32
        }

### Get faqs [GET]

+ Response 200 (application/json)

        {
            "results": [
                {
                    "id": 1,
                    "fields": [
                        {
                            "name": "answer",
                            "type": "rich_text",
                            "value": {
                                "blocks": [
                                    {
                                        "data": {},
                                        "depth": 0,
                                        "entityRanges": [],
                                        "inlineStyleRanges": [],
                                        "key": "5gia1",
                                        "text": "Commentary: Chicago's police crisis fall on all of us",
                                        "type": "unstyled"
                                    }
                                ],
                                "entityMap": {}
                            }
                        },
                        {
                            "name": "question",
                            "type": "rich_text",
                            "value": {
                                "blocks": [
                                    {
                                        "data": {},
                                        "depth": 0,
                                        "entityRanges": [],
                                        "inlineStyleRanges": [],
                                        "key": "a4b9s",
                                        "text": "The “few bad apples” theory of police violence posits that a small portion of the police force is ill-intentioned or inclined to misconduct or violence, while the majority of officers are good cops. Until recently, this theory was difficult for civilians to investigate, but department data on complaints against officers obtained through a legal challenge shows that police misconduct in Chicago is overwhelmingly the product of a small fraction of officers and that it may be possible to identify those officers and reduce misconduct.",
                                        "type": "unstyled"
                                    },
                                    {
                                        "data": {},
                                        "depth": 0,
                                        "entityRanges": [],
                                        "inlineStyleRanges": [],
                                        "key": "a4b9z",
                                        "text": "This far-reaching data set, a product of the nonprofit Invisible Institute’s Citizens Police Data Project, comprehensively covers nearly five years of complaints against Chicago police officers. Each of the 28,588 records in the database offers a detailed account of the incident, including information on the accused officer, the complainant, the type of alleged misconduct, and whether the complaint was found legitimate by an internal investigation.",
                                        "type": "unstyled"
                                    }
                                ],
                                "entityMap": {}
                            }
                        }
                    ],
                    "meta": {
                        "order": 1,
                        "starred": true
                    }
                }
            ]
        }

## Bulk Update FAQs [/faqs/bulk-update/]

### Bulk Update FAQs [PATCH]

+ Request  (application/json)

    + Headers

            Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b

    + Body

            [
                {
                    "id": 1,
                    "meta": {
                        "order": 1
                    }
                },
                {
                    "id": 2,
                    "meta": {
                        "order": 2
                    }
                }
            ]

+ Response 200 (application/json)

        [

            {
                "id": 1,
                "fields": [
                    {
                        "name": "answer",
                        "type": "rich_text",
                        "value": {
                            "blocks": [
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "5gia1",
                                    "text": "Commentary: Chicago's police crisis fall on all of us",
                                    "type": "unstyled"
                                }
                            ],
                            "entityMap": {}
                        }
                    },
                    {
                        "name": "question",
                        "type": "rich_text",
                        "value": {
                            "blocks": [
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "a4b9s",
                                    "text": "The “few bad apples” theory of police violence posits that a small portion of the police force is ill-intentioned or inclined to misconduct or violence, while the majority of officers are good cops. Until recently, this theory was difficult for civilians to investigate, but department data on complaints against officers obtained through a legal challenge shows that police misconduct in Chicago is overwhelmingly the product of a small fraction of officers and that it may be possible to identify those officers and reduce misconduct.",
                                    "type": "unstyled"
                                },
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "a4b9z",
                                    "text": "This far-reaching data set, a product of the nonprofit Invisible Institute’s Citizens Police Data Project, comprehensively covers nearly five years of complaints against Chicago police officers. Each of the 28,588 records in the database offers a detailed account of the incident, including information on the accused officer, the complainant, the type of alleged misconduct, and whether the complaint was found legitimate by an internal investigation.",
                                    "type": "unstyled"
                                }
                            ],
                            "entityMap": {}
                        }
                    }
                ],
                "meta": {
                    "order": 1,
                    "starred": false
                }
            }
        ]


## FAQ detail [/faqs/{faq_id}/]

+ Parameters
    + faq_id (number) - number ID of the faq item

### Get FAQ [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "fields": [
                {
                    "name": "answer",
                    "type": "rich_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "5gia1",
                                "text": "Commentary: Chicago's police crisis fall on all of us",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "question",
                    "type": "rich_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a4b9s",
                                "text": "The “few bad apples” theory of police violence posits that a small portion of the police force is ill-intentioned or inclined to misconduct or violence, while the majority of officers are good cops. Until recently, this theory was difficult for civilians to investigate, but department data on complaints against officers obtained through a legal challenge shows that police misconduct in Chicago is overwhelmingly the product of a small fraction of officers and that it may be possible to identify those officers and reduce misconduct.",
                                "type": "unstyled"
                            },
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a4b9z",
                                "text": "This far-reaching data set, a product of the nonprofit Invisible Institute’s Citizens Police Data Project, comprehensively covers nearly five years of complaints against Chicago police officers. Each of the 28,588 records in the database offers a detailed account of the incident, including information on the accused officer, the complainant, the type of alleged misconduct, and whether the complaint was found legitimate by an internal investigation.",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                }
            ],
            "meta": {
                "order": 1,
                "starred": false
            }
        }

### Partial Update FAQ [PATCH]

This api require an api access token set in `Authorization` header. To get an api access token, use **Sign In** api.

+ Request (application/json)

    + Headers

            Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b

    + Body

            {
                "fields": [
                    {
                        "name": "answer",
                        "type": "rich_text",
                        "value": {
                            "blocks": [
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "5gia1",
                                    "text": "Commentary: Chicago's police crisis fall on all of us",
                                    "type": "unstyled"
                                }
                            ],
                            "entityMap": {}
                        }
                    },
                    {
                        "name": "question",
                        "type": "rich_text",
                        "value": {
                            "blocks": [
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "a4b9s",
                                    "text": "The “few bad apples” theory of police violence posits that a small portion of the police force is ill-intentioned or inclined to misconduct or violence, while the majority of officers are good cops. Until recently, this theory was difficult for civilians to investigate, but department data on complaints against officers obtained through a legal challenge shows that police misconduct in Chicago is overwhelmingly the product of a small fraction of officers and that it may be possible to identify those officers and reduce misconduct.",
                                    "type": "unstyled"
                                },
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "a4b9z",
                                    "text": "This far-reaching data set, a product of the nonprofit Invisible Institute’s Citizens Police Data Project, comprehensively covers nearly five years of complaints against Chicago police officers. Each of the 28,588 records in the database offers a detailed account of the incident, including information on the accused officer, the complainant, the type of alleged misconduct, and whether the complaint was found legitimate by an internal investigation.",
                                    "type": "unstyled"
                                }
                            ],
                            "entityMap": {}
                        }
                    }
                ],
                "meta": {
                    "order": 1,
                    "starred": false
                }
            }

+ Response 200 (application/json)

        {
            "id": 1,
            "fields": [
                {
                    "name": "answer",
                    "type": "rich_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "5gia1",
                                "text": "Commentary: Chicago's police crisis fall on all of us",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "question",
                    "type": "rich_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a4b9s",
                                "text": "The “few bad apples” theory of police violence posits that a small portion of the police force is ill-intentioned or inclined to misconduct or violence, while the majority of officers are good cops. Until recently, this theory was difficult for civilians to investigate, but department data on complaints against officers obtained through a legal challenge shows that police misconduct in Chicago is overwhelmingly the product of a small fraction of officers and that it may be possible to identify those officers and reduce misconduct.",
                                "type": "unstyled"
                            },
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a4b9z",
                                "text": "This far-reaching data set, a product of the nonprofit Invisible Institute’s Citizens Police Data Project, comprehensively covers nearly five years of complaints against Chicago police officers. Each of the 28,588 records in the database offers a detailed account of the incident, including information on the accused officer, the complainant, the type of alleged misconduct, and whether the complaint was found legitimate by an internal investigation.",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                }
            ],
            "meta": {
                "order": 1,
                "starred": false
            }
        }

## Analytic events [/events/]

### Create Event [POST]

+ Request (application/json)

    + Body

            {
                "name": "faq-click",
                "data": {
                    "id": 12,
                    "title": "How accurate is the data?",
                    "timestamp": "2017-01-23T03:11:53Z"
                }
            }

+ Response 201

## Officer summary [/officers/{officer_id}/summary]

### Get Officer Summary [GET]

+ Parameters
    + officer_id (number) - number ID of the officer

+ Response 200 (application/json)

        {
            "id": 1,
            "unit": "003",
            "date_of_appt": "2015-09-23",
            "date_of_resignation": "2017-09-23",
            "active": "Active",
            "rank": "NA",
            "race": "White",
            "badge": "12345",
            "gender": "Male",
            "birth_year": 1951
        }

## Officer summary [/officers/{officer_id}/metrics]

### Get Officer Metrics [GET]

+ Parameters
    + officer_id (number) - number ID of the officer

+ Response 200 (application/json)

        {
            "id": 8562,
            "allegation_count": 90,
            "civilian_compliment_count": 0,
            "discipline_count": 0,
            "honorable_mention_count": 1,
            "sustained_count": 4,
            "complaint_percentile": 40.0
        }

## Officer percentile [/officers/{officer_id}/percentile]

### Get Officer Percentile group by year [GET]

+ Parameters
    + officer_id (number) - number ID of the officer

+ Response 200 (application/json)

        [
            {
                "officer_id": 1,
                "year": 2016,
                "percentile_trr": "0.000",
                "percentile_allegation": "76.282",
                "percentile_allegation_civilian": "79.479",
                "percentile_allegation_internal": "0.000"
            },
            {
                "officer_id": 1,
                "year": 2017,
                "percentile_trr": "0.000",
                "percentile_allegation": "58.446",
                "percentile_allegation_civilian": "63.044",
                "percentile_allegation_internal": "0.000"
            }
        ]

## Officer timeline minimap [/officers/{officer_id}/timeline-minimap]

### Get Officer timeline minimap [GET]

+ Parameters
    + officer_id (number) - number ID of the officer

+ Response 200 (application/json)

        [
            {
                "kind": "cr",
                "year": 2016
            },
            {
                "kind": "trr",
                "year": 2015
            }
        ]

## Officer timeline items list [/officers/{officer_id}/timeline-items]

### Get Officer timeline items list [GET]

+ Parameters
    + officer_id (number) - number ID of the officer

+ Response 200 (application/json)

        {
            "count": 20,
            "previous": null,
            "next": "http://cpdp.co/officers/123/timeline-items/?offset=20"
            "results": [
                {
                    "kind": "YEAR",
                    "crs": 2,
                    "year": 2016,
                    "trrs": 0,
                    "salary": 46492.96
                },
                {
                    "kind": "CR",
                    "crid": "307965",
                    "category": "Illegal Search",
                    "subcategory": "Search of premise/vehicle without warrant",
                    "finding": "Unfounded",
                    "coaccused": 4,
                    "date": "2016-08-24"
                },
                {
                    "kind": "UNIT_CHANGE",
                    "unit_name": "003",
                    "date": "2016-08-24"
                },
                {
                    "kind": "JOINED",
                    "date": "2012-08-24"
                }
            ]
        }

## Officer social graph [/officers/{officer_id}/social-graph]

### Get Officer social graph [GET]

+ Parameters
    + officer_id (number) - number ID of the officer

+ Response 200 (application/json)

        {
            "links": [
                {
                    "source": 1,
                    "target": 2,
                    "cr_years": [2009, 2011]
                }
            ],
            "nodes": [
                {
                    "id": 1,
                    "name": "Clarence Featherwater",
                    "cr_years": [null, 1984, 2009, 2009, 2011]
                },
                {
                    "id": 2,
                    "name": "Raymond Piwnicki",
                    "cr_years": [2009, 2011]
                }
            ]
        }

## Top Officers by allegation [/officers/top-by-allegation/{?random}]

### Get Officer cards on top 1% complaint percentile [GET]

+ Parameters
    + random (optional, 1 or 0) - 1: randomize the result, default 0: sort complaint_percentile by descending

+ Response 200 (application/json)

        [
            {
                "id": 8658,
                "visual_token_background_color": "#90b1f5",
                "full_name": "Corey Flagg",
                "complaint_count": 67,
                "sustained_count": 5,
                "birth_year": 1970,
                "complaint_percentile": 99.995,
                "race": "Black",
                "gender": "Male",
                "percentile": {
                    "officer_id": 8658,
                    "year": 2017,
                    "percentile_trr": "0.000",
                    "percentile_allegation": "99.995",
                    "percentile_allegation_civilian": "99.990",
                    "percentile_allegation_internal": "99.795"
                }
            },
            {
                "id": 13788,
                "visual_token_background_color": "#90b1f5",
                "full_name": "Broderick Jones",
                "complaint_count": 69,
                "sustained_count": 8,
                "birth_year": 1971,
                "complaint_percentile": 99.99,
                "race": "Black",
                "gender": "Male",
                "percentile": {
                    "officer_id": 13788,
                    "year": 2017,
                    "percentile_trr": "0.000",
                    "percentile_allegation": "99.990",
                    "percentile_allegation_civilian": "99.995",
                    "percentile_allegation_internal": "90.565"
                }
            }
        ]

## CR [/cr/complaint-summaries/]

### List recent updated Summary of CR [GET]

+ Response 200 (application/json)

        [
            {
                "crid": "1080158",
                "category_names": [
                    "Unknown"
                ],
                "incident_date": "2016-04-18",
                "summary": "Officer A was off-duty and inside her residence when she reportedly ..."
            },
            {
                "crid": "1079959",
                "category_names": [
                    "Unknown"
                ],
                "incident_date": "2016-04-05",
                "summary": "Subject and the off-duty Officer A had a motor vehicle accident in which Subject ..."
            }
        ]

## CR [/mobile/cr/{crid}/]

### Get CR [GET]

+ Parameters
    + crid (number) - number ID of Allegation

+ Response 200 (application/json)

        {
            "crid": "12345",
            "coaccused": [
                {
                    "id": 123,
                    "full_name": "Robert O’Niell",
                    "gender": "Male",
                    "race": "White",
                    "final_finding": "Sustained",
                    "recc_outcome": "Separation",
                    "final_outcome": "Repriment",
                    "category": "Operation/Personnel Violations",
                    "subcategory": "NEGLECT OF DUTY/CONDUCT UNBECOMING - ON DUTY",
                    "start_date": "2003-12-12",
                    "end_date": "2004-12-12"
                }
            ],
            "complainants": [
                {
                    "race": "White",
                    "gender": "Male",
                    "age": 18
                },
                {
                    "race": "Black",
                    "gender": "Female",
                    "age": 20
                }
            ],
            "point": {
                "long": -87.664606,
                "lat": 41.68731
            },
            "incident_date": "2002-02-28",
            "address": "3510 Michigan Ave, Chicago, IL 60653",
            "location": "Police Building",
            "beat": {
                "name": "23"
            },
            "involvements": [
                {
                    "involved_type": "investigator",
                    "officers": [
                        {
                            "id": 1,
                            "abbr_name": "L. Skol",
                            "extra_info": "126 cases"
                        }
                    ]
                },
                {
                    "involved_type": "police witnesses",
                    "officers": [
                        {
                            "id": 2,
                            "abbr_name": "R. Piwinicki",
                            "extra_info": "male, white"
                        },
                        {
                            "id": 3,
                            "abbr_name": "J. Ipsum",
                            "extra_info": "male, black"
                        }
                    ]
                }
            ],
            "audios": [
                {
                    "title": "CHI - R-00001275 Red",
                    "url": "http://foo.com"
                }
            ],
            "videos": [
                {
                    "title": "CHI - R-00001275 Red",
                    "url": "http://foo.com"
                }
            ],
            "documents": [
                {
                    "title": "CHI - R-00001275 Red",
                    "url": "http://foo.com"
                }
            ]
        }


## CR [/cr/{crid}/]

### Get CR [GET]

+ Parameters
    + crid (number) - number ID of Allegation

+ Response 200 (application/json)

        {
            "crid": "12345",
            "coaccused": [
                {
                    "id": 123,
                    "full_name": "Robert O’Niell",
                    "gender": "Male",
                    "race": "White",
                    "age": 41,
                    "allegation_count": 43,
                    "sustained_count": 1,
                    "final_outcome": "Reprimand",
                    "category": "Operation/Personnel Violations",
                    "percentile_allegation": 99.861,
                    "percentile_allegation_civilian": 99.881,
                    "percentile_allegation_internal": 80.569,
                    "percentile_trr": 92.110
                },
                {
                    "id": 456,
                    "full_name": "Alex Foo",
                    "gender": "Male",
                    "race": "Black",
                    "age": 36,
                    "allegation_count": 23,
                    "sustained_count": 0,
                    "final_outcome": "Unknown",
                    "category": "Operation/Personnel Violations",
                    "percentile_allegation": 99.861,
                    "percentile_allegation_civilian": 99.881,
                    "percentile_allegation_internal": 80.569,
                    "percentile_trr": 92.110
                }
            ],
            "complainants": [
                {
                    "race": "White",
                    "gender": "Male",
                    "age": 18
                },
                {
                    "race": "Black",
                    "gender": "Female",
                    "age": 20
                }
            ],
            "victims": [
                {
                    "race": "Black",
                    "gender": "Male",
                    "age": 53
                },
                {
                    "race": "Black",
                    "gender": "Female",
                    "age": 20
                }
            ],
            "summary": "Lorem ipsum dolor.",
            "point": {
                "lon": -87.664606,
                "lat": 41.68731
            },
            "incident_date": "2002-02-28",
            "start_date": "2002-02-30",
            "end_date": "2002-04-21",
            "address": "3510 Michigan Ave, Chicago, IL 60653",
            "location": "Police Building",
            "beat": "23",
            "involvements": [
                {
                    "officer_id": 1,
                    "involved_type": "investigator",
                    "full_name": "Lauren Skol",
                    "current_rank": "IPRA investigator",
                    "percentile_allegation_civilian": 99.881,
                    "percentile_allegation_internal": 80.569,
                    "percentile_trr": 92.110
                },
                {
                    "officer_id": 2,
                    "involved_type": "police_witness",
                    "full_name": "Raymond Piwinicki",
                    "allegation_count": 10,
                    "sustained_count": 3,
                    "percentile_allegation_civilian": 99.881,
                    "percentile_allegation_internal": 80.569,
                    "percentile_trr": 92.110
                },
                {
                    "officer_id": 3,
                    "involved_type": "police_witness",
                    "full_name": "German Felix",
                    "allegation_count": 10,
                    "sustained_count": 3,
                    "percentile_allegation_civilian": 99.881,
                    "percentile_allegation_internal": 80.569,
                    "percentile_trr": 92.110
                }
            ],
            "attachments": [
                {
                    "title": "CHI - R-00001275 Red",
                    "file_type": "video",
                    "url": "http://foo.com",
                    "preview_image_url": "http://foo.com/bar.jpg"
                },
                {
                    "title": "CHI - R-00001275 Red",
                    "file_type": "audio",
                    "url": "http://foo.com",
                    "preview_image_url": "http://foo.com/bar.jpg"
                },
                {
                    "title": "CHI - R-00001275 Red",
                    "file_type": "document",
                    "url": "http://foo.com",
                    "preview_image_url": "http://foo.com/bar.jpg"
                }
            ]
        }


## Search Aliases [/aliases/{aliasType}/{id}/]

### Update search aliases for a search result [POST]

+ Parameters
    + aliasType (string) - Can be officer/neighborhood/community/faq/report/unit
    + id (number) - Primary key of search result

+ Request (application/json)

        {
            aliases: ["foo", "bar"]
        }

+ Response 200 (application/json)

        {
            "message": "Aliases successfully updated",
            "aliases": ["foo", "bar"]
        }

+ Request (application/json)

        {
            aliases: ["an alias that is absolutely way too long"]
        }

+ Response 400 (application/json)

        {
            "message": {
                "aliases": ["Ensure this field has no more than 20 characters."]
            }
        }


## CR Documents [/cr/{crid}/request-document/]

### Request document [POST]

+ Parameters
    + crid (number) - number ID of Allegation

+ Request (application/json)

        {
            "email": "asdf@example.com"
        }

+ Response 200 (application/json)

        {
            "crid": "293928",
            "message": "Thanks for subscribing"
        }

+ Request (application/json)

        {
            "email": "already_used@example.com"
        }

+ Response 200 (application/json)

        {
            "crid": "293928",
            "message": "Email already added"
        }

+ Request (application/json)

        {
            "email": "malformed email"
        }

+ Response 400 (application/json)

        {
            "message": "Please enter a valid email"
        }

## CR Documents [/cr/list-by-new-document]

### List document which has new documents (in document-cloud) [GET]

+ Parameters
    + limit (number) - number of allegations which has new document

+ Response 200 (application/json)
        [
            {
                "crid": "111",
                "latest_document": {
                    "title": "CR document 1",
                    "url": "http://cr-document.com/1",
                    "preview_image_url": "http://preview.com/url"
                },
                "num_recent_documents": 2
            },
            {
                "crid": "112",
                "latest_document": {
                    "title": "CR document 3",
                    "url": "http://cr-document.com/3",
                    "preview_image_url": "http://preview.com/url3"
                },
                "num_recent_documents": 1
            },
        ]



## Unit summary [/units/{unit_id}/summary]

### Get Unit Summary [GET]

+ Parameters
    + unit_id (number) - number ID of the unit

+ Response 200 (application/json)

        {
            "unit_name": "001",
            "member_records": {
                "active_members": 72,
                "total": 156,
                "facets": [
                    {
                        "name": "race",
                        "entries": [
                            {
                                "name": "White",
                                "count": 10
                            },
                            {
                                "name": "Unknown",
                                "count": 1
                            }
                        ]
                    },
                    {
                        "name": "age",
                        "entries": [
                            {
                                "name": "21-30",
                                "count": 10
                            },
                            {
                                "name": "51+",
                                "count": 2
                            }
                        ]
                    },
                    {
                        "name": "gender",
                        "entries": [
                            {
                                "name": "Male",
                                "count": 10
                            },
                            {
                                "name": "Female",
                                "count": 6
                            },
                            {
                                "name": "X",
                                "count": 4
                            },
                            {
                                "name": "Unknown",
                                "count": 2
                            }
                        ]
                    }
                ]
            },
            "complaint_records": {
                "count": 27,
                "sustained_count": 3,
                "facets": [
                    {
                        "name": "category",
                        "entries": [
                            {
                                "name": "Illegal Search",
                                "count": 12,
                                "sustained_count": 2
                            }
                        ]
                    },
                    {
                        "name": "race"
                        "entries": [
                            {
                                "name": "White",
                                "count": 9,
                                "sustained_count": 1
                            }
                        ]
                    },
                    {
                        "name": "age",
                        "entries": [
                            {
                                "name": "21-30",
                                "count": 5,
                                "sustained_count": 0
                            }
                        ]
                    },
                    {
                        "name": "gender",
                        "entries": [
                            {
                                "name": "Female",
                                "count": 2,
                                "sustained_count": 0
                            }
                        ]
                    }
                ]
            }
        }


## Activity grid [/activity-grid/]

### Get activity cards [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "full_name": "Jerome Finnigan",
                "visual_token_background_color": "#90b1f5",
                "birth_year": 1963,
                "complaint_count": 90,
                "complaint_percentile": 88.55,
                "gender": "Male"
                "race": "White",
                "sustained_count": 4,
                "percentile": {
                    "officer_id": 5193,
                    "year": 2017,
                    "percentile_trr": "91.696",
                    "percentile_allegation": "99.870",
                    "percentile_allegation_civilian": "99.895",
                    "percentile_allegation_internal": "80.494"
                }
            },
            {
                "id": 2,
                "full_name": "Raymond Piwnicki",
                "visual_token_background_color": "#aec9e8",
                "birth_year": 1963,
                "complaint_count": 89,
                "complaint_percentile": None,
                "gender": "Male"
                "race": "White",
                "sustained_count": 6,
                "percentile": {
                    "officer_id": 5193,
                    "year": 2017,
                    "percentile_trr": "91.696",
                    "percentile_allegation": "99.870",
                    "percentile_allegation_civilian": "99.895",
                    "percentile_allegation_internal": "80.494"
                }
            }
        ]

## Search term categories list [/search-term-categories/]

### Get Search term categories [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Geography",
                "items": [
                    {
                        "name": "Police Districts",
                        "description": "A form of division of a geographical area patrolled by a police force",
                        "id": "police-districts",
                        "call_to_action_type": "view_all"
                    }
                ]
            },
            {
                "name": "Officers",
                "items": [
                    {
                        "name": "Officer Name",
                        "description": "Type the name of an officer into the search bar",
                        "id": "officer-name",
                        "call_to_action_type": "plain_text"
                    }
                ]
            },
            {
                "name": "Complaint Categories",
                "items": [
                    {
                        "name": "Conduct Unbecoming",
                        "description": "Search the data tool for Conduct Unbecoming",
                        "id": "conduct-unbecoming",
                        "call_to_action_type": "link",
                        "link": "http://beta.cpdb.co/url-mediator/session-builder?cat__category=Conduct%20Unbecoming"
                    }
                ]
            }
        ]

## General search [/v1/suggestion/{term}/?limit={limit}]

+ Parameters
    + term (string) - Search term
    + limit (number) - Django REST framework limit pagination

### Get search results [GET]

+ Response 200 (application/json)

        {
          "NEIGHBORHOOD": [
            {
              "text": "Washington Heights",
              "payload": {
                "result_text": "Washington Heights",
                "url": "http://staging.cpdb.co/url-mediator/session-builder?neighborhood=Washington Heights",
                "tags": []
              },
              "id": "345"
            },
            {
              "text": "Washington Park",
              "payload": {
                "result_text": "Washington Park",
                "url": "http://staging.cpdb.co/url-mediator/session-builder?neighborhood=Washington Park",
                "tags": []
              },
              "id": "339"
            }
          ],
          "CO-ACCUSED": [
            {
              "text": "Henry Thomas",
              "payload": {
                "result_text": "Henry Thomas",
                "to": "/officer/28416/",
                "result_extra_information": "Badge # 20455",
                "result_reason": "coaccused with Walter Ware (17626)"
              },
              "id": "AV_JHHFVEEvAIPTOfirI"
            },
            {
              "text": "Geno Rouse",
              "payload": {
                "result_text": "Geno Rouse",
                "to": "/officer/32306/",
                "result_extra_information": "Badge # 2155",
                "result_reason": "coaccused with Walter Ware (17626)"
              },
              "id": "AV_JHHFfEEvAIPTOfirL"
            },
          ],
          "COMMUNITY": [
            {
              "text": "Washington Heights",
              "payload": {
                "result_text": "Washington Heights",
                "url": "http://staging.cpdb.co/url-mediator/session-builder?community=Washington Heights",
                "tags": []
              },
              "id": "497"
            },
            {
              "text": "Washington Park",
              "payload": {
                "result_text": "Washington Park",
                "url": "http://staging.cpdb.co/url-mediator/session-builder?community=Washington Park",
                "tags": []
              },
              "id": "432"
            }
          ],
          "UNIT": [],
          "UNIT > OFFICERS": [],
          "OFFICER": [
            {
              "text": "Tommy Walker",
              "payload": {
                "visual_token_background_color": "#90b1f5",
                "result_extra_information": "Badge # 2328",
                "rank": "Sergeant Of Police",
                "sex": "Male",
                "result_reason": "",
                "unit": "005",
                "salary": null,
                "result_text": "Tommy Walker",
                "tags": [],
                "to": "/officer/29841/",
                "race": "Black"
              },
              "id": "29841"
            },
            {
              "text": "Corey Walker",
              "payload": {
                "visual_token_background_color": "#90b1f5",
                "result_extra_information": "Badge # 1730",
                "rank": "Sergeant Of Police",
                "sex": "Male",
                "result_reason": "",
                "unit": "008",
                "salary": null,
                "result_text": "Corey Walker",
                "tags": [],
                "to": "/officer/29833/",
                "race": "Black"
              },
              "id": "29833"
            },
          ]
        }


## Specific type search [/v1/suggestion/{term}/single/?contentType={type}]

+ Parameters
    + term (string) - Search term
    + type (string) - Data content type (OFFICER, UNIT, COMMUNITY, NEIGHBORHOOD, CO-ACCUSED, UNIT > OFFICERS)

### Get search results [GET]

+ Response 200 (application/json)

        {
          "count": 2,
          "previous": null,
          "next": null,
          "results": [
            {
              "text": "Orson Ward",
              "payload": {
                "visual_token_background_color": "#c6d4ec",
                "result_extra_information": "Badge # 13603",
                "rank": "Police Officer",
                "sex": "Male",
                "result_reason": "",
                "unit": "010",
                "salary": null,
                "result_text": "Orson Ward",
                "tags": [],
                "to": "/officer/30022/",
                "race": "Black"
              },
              "id": "30022"
            },
            {
              "text": "Orson Kallenback",
              "payload": {
                "visual_token_background_color": "#f5f4f4",
                "result_extra_information": "",
                "rank": "Police Officer",
                "sex": "Male",
                "result_reason": "",
                "unit": "169",
                "salary": null,
                "result_text": "Orson Kallenback",
                "tags": [],
                "to": "/officer/14026/",
                "race": "White"
              },
              "id": "14026"
            }
          ]
        }


## City Summary [/v2/city-summary/]

### Get city summary [GET]

+ Response 200 (application/json)

        {
            "allegation_count": 125735,
            "most_common_complaints": [
                {
                    "name": "Operation/Personnel Violations",
                    "count": 1
                },
                {
                    "name": "Use Of Force",
                    "count": 1
                },
                {
                    "name": "Illegal Search",
                    "count": 1
                },
            ],
            "discipline_count": 6404
        }
