FORMAT: 1A
HOST: https://cpdp.docs.apiary.io/

# CPDP

CPDP is a simple API serving the CPDP website version 2 (not the same as api version) now live at https://beta.cpdp.co. It includes two main portions: CMS and data tool.

**Conventions**:

- Property name is in snake case: `field_name` instead of `fieldName`

## CMS Page [/cms-pages/{page_id}/]

+ Parameters
    + page_id (string) - ID of the Page that look like a slug

### Get CMS page content [GET]

**Properties**:

- `fields` is an array of fields. Each fields has `name`, `type` and `value`. `value` is an opaque object that should be only of interest to whatever module that deal with it directly. As such it's content might violate some of conventions followed elsewhere such as having property name be in snake case.

+ Response 200 (application/json)

        {
            "fields": [
                {
                    "name": "vftg_date",
                    "type": "date",
                    "value": "2016-10-07"
                },
                {
                    "name": "vftg_link",
                    "type": "link",
                    "value": "https://google.com"
                },
                {
                    "name": "vftg_content",
                    "type": "plain_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "5gia1",
                                "text": "Real Independence for Police Oversight Agencies",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "collaborate_header",
                    "type": "plain_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "5gia1",
                                "text": "Collaborate With Us.",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "collaborate_content",
                    "type": "multiline_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a4b9s",
                                "text": "We are collecting and publishing information that sheds light on police misconduct.",
                                "type": "unstyled"
                            },
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a4b9z",
                                "text": "If you have documents or datasets you would like to publish, please email us, or learn more.",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "about_header",
                    "type": "plain_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a89s0",
                                "text": "About",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "about_content",
                    "type": "multiline_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a9sn8",
                                "text": "The Citizens Police Data Project houses police disciplinary information obtained from the City of Chicago..",
                                "type": "unstyled"
                            },
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a9sn5",
                                "text": "The information and stories we have collected here are intended as a resource for public oversight. Our aim is to create a new model of accountability between officers and citizens.",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                }
            ]
        }

### Partial update CMS page content [PATCH]

This api require an api access token set in `Authorization` header. To get an api access token, use **Sign In** api.

+ Request (application/json)

    + Headers

            Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b

    + Body

            {
                "fields": [
                    {
                        "name": "collaborate_header",
                        "type": "plain_text",
                        "value": {
                            "blocks": [
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "5gia1",
                                    "text": "Collaborate With Us.",
                                    "type": "unstyled"
                                }
                            ],
                            "entityMap": {}
                        }
                    },
                    {
                        "name": "collaborate_content",
                        "type": "multiline_text",
                        "value": {
                            "blocks": [
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "a4b9s",
                                    "text": "We are collecting and publishing information that sheds light on police misconduct.",
                                    "type": "unstyled"
                                },
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "a4b9z",
                                    "text": "If you have documents or datasets you would like to publish, please email us, or learn more.",
                                    "type": "unstyled"
                                }
                            ],
                            "entityMap": {}
                        }
                    }
                ]
            }

+ Response 200 (application/json)

            {
                "fields": [
                {
                    "name": "vftg_date",
                    "type": "date",
                    "value": "2016-10-07"
                },
                {
                    "name": "vftg_link",
                    "type": "link",
                    "value": "https://google.com"
                },
                {
                    "name": "vftg_content",
                    "type": "plain_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "5gia1",
                                "text": "Real Independence for Police Oversight Agencies",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "collaborate_header",
                    "type": "plain_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "5gia1",
                                "text": "Collaborate With Us.",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "collaborate_content",
                    "type": "multiline_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a4b9s",
                                "text": "We are collecting and publishing information that sheds light on police misconduct.",
                                "type": "unstyled"
                            },
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a4b9z",
                                "text": "If you have documents or datasets you would like to publish, please email us, or learn more.",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "about_header",
                    "type": "plain_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a89s0",
                                "text": "About",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                },
                {
                    "name": "about_content",
                    "type": "multiline_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a9sn8",
                                "text": "The Citizens Police Data Project houses police disciplinary information obtained from the City of Chicago..",
                                "type": "unstyled"
                            },
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "a9sn5",
                                "text": "The information and stories we have collected here are intended as a resource for public oversight. Our aim is to create a new model of accountability between officers and citizens.",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                }
            ]
        }

+ Request (application/json)

        {
            "fields": [
                {
                    "name": "collaborate_header",
                    "type": "plain_text",
                    "value": {
                        "blocks": [
                            {
                                "data": {},
                                "depth": 0,
                                "entityRanges": [],
                                "inlineStyleRanges": [],
                                "key": "5gia1",
                                "text": "Collaborate With Us.",
                                "type": "unstyled"
                            }
                        ],
                        "entityMap": {}
                    }
                }
            ]
        }

+ Response 401 (application/json)

    + Headers

            WWW-Authenticate: Token

## Sign In [/users/sign-in/]

### Sign in and get an api access token [POST]

+ Request (application/json)

        {
            "username": "admin",
            "password": "admin@123"
        }

+ Response 200 (application/json)

        {
            "apiAccessToken": "9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b"
        }

+ Request (application/json)

        {
            "username": "incorrectname",
            "password": "password"
        }

+ Response 400 (application/json)

        {
            "message": "Sorry, you‚Äôve entered an incorrect name."
        }

+ Request (application/json)

        {
            "username": "admin",
            "password": "incorrect"
        }

+ Response 400 (application/json)

        {
            "message": "You‚Äôve entered an incorrect password."
        }

## Forgot password [/users/forgot-password/]

### Forgot password [POST]

+ Request (application/json)

        {
            "email": "admin@domain.com"
        }

+ Response 200 (application/json)

        {
            "message": "Please check your email for a password reset link."
        }

+ Request (application/json)

        {
            "email": "unregistered@email.co"
        }

+ Response 400 (application/json)

        {
            "message": "Sorry, there‚Äôs no account registered with this email address."
        }

### Partial Update report [PATCH]

This api require an api access token set in `Authorization` header. To get an api access token, use **Sign In** api.

+ Request (application/json)

    + Headers

            Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b

    + Body

            {
                "fields": [
                    {
                        "name": "title",
                        "type": "plain_text",
                        "value": {
                            "blocks": [
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "5gia1",
                                    "text": "Commentary: Chicago's police crisis fall on all of us",
                                    "type": "unstyled"
                                }
                            ],
                            "entityMap": {}
                        }
                    },
                    {
                        "name": "excerpt",
                        "type": "multiline_text",
                        "value": {
                            "blocks": [
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "a4b9s",
                                    "text": "The “few bad apples” theory of police violence posits that a small portion of the police force is ill-intentioned or inclined to misconduct or violence, while the majority of officers are good cops. Until recently, this theory was difficult for civilians to investigate, but department data on complaints against officers obtained through a legal challenge shows that police misconduct in Chicago is overwhelmingly the product of a small fraction of officers and that it may be possible to identify those officers and reduce misconduct.",
                                    "type": "unstyled"
                                },
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "a4b9z",
                                    "text": "This far-reaching data set, a product of the nonprofit Invisible Institute‚Äôs Citizens Police Data Project, comprehensively covers nearly five years of complaints against Chicago police officers. Each of the 28,588 records in the database offers a detailed account of the incident, including information on the accused officer, the complainant, the type of alleged misconduct, and whether the complaint was found legitimate by an internal investigation.",
                                    "type": "unstyled"
                                }
                            ],
                            "entityMap": {}
                        }
                    }
                ]
            }

+ Response 200 (application/json)

            {
                "id": 1,
                "fields": [
                    {
                        "name": "title",
                        "type": "plain_text",
                        "value": {
                            "blocks": [
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "5gia1",
                                    "text": "Commentary: Chicago's police crisis",
                                    "type": "unstyled"
                                }
                            ],
                            "entityMap": {}
                        }
                    },
                    {
                        "name": "excerpt",
                        "type": "multiline_text",
                        "value": {
                            "blocks": [
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "a4b9s",
                                    "text": "The “few bad apples” theory of police violence posits that a small portion of the police force is ill-intentioned or inclined to misconduct or violence, while the majority of officers are good cops. Until recently, this theory was difficult for civilians to investigate, but department data on complaints against officers obtained through a legal challenge shows that police misconduct in Chicago is overwhelmingly the product of a small fraction of officers and that it may be possible to identify those officers and reduce misconduct.",
                                    "type": "unstyled"
                                },
                                {
                                    "data": {},
                                    "depth": 0,
                                    "entityRanges": [],
                                    "inlineStyleRanges": [],
                                    "key": "a4b9z",
                                    "text": "This far-reaching data set, a product of the nonprofit Invisible Institute‚Äôs Citizens Police Data Project, comprehensively covers nearly five years of complaints against Chicago police officers. Each of the 28,588 records in the database offers a detailed account of the incident, including information on the accused officer, the complainant, the type of alleged misconduct, and whether the complaint was found legitimate by an internal investigation.",
                                    "type": "unstyled"
                                }
                            ],
                            "entityMap": {}
                        }
                    },
                    {
                        "name": "publication",
                        "type": "string",
                        "value": "New York Times"
                    },
                    {
                        "name": "publish_date",
                        "type": "date",
                        "value": "2016-09-23"
                    },
                    {
                        "name": "author",
                        "type": "string",
                        "value": "Edgar Sterling"
                    },
                    {
                        "name": "officers",
                        "type": "officers_list",
                        "value": [
                            {
                                "id": 123,
                                "full_name": "Edgar Davis",
                                "allegation_count": 14,
                                "v1_url": "http://cpdb.co/officer/edgar/123",
                                "gender": "Male",
                                "race": "White"
                            }
                        ]
                    }
                ]

        }

## Analytic events [/events/]

### Create Event [POST]

+ Request (application/json)

    + Body

            {
                "name": "some-click",
                "data": {
                    "id": 12,
                    "title": "How accurate is the data?",
                    "timestamp": "2017-01-23T03:11:53Z"
                }
            }

+ Response 201

## Officer summary [/officers/{officer_id}/summary]

### Get Officer Summary (include bio, metrics, and yearly percentiles) [GET]

+ Parameters
    + officer_id (number) - number ID of the officer

+ Response 200 (application/json)

        {
            "id": 1,
            "unit": {
                "id": 1,
                "unit_name": "001",
                "description": "Unit 001"
            },
            "date_of_appt": "2015-09-23",
            "date_of_resignation": "2017-09-23",
            "active": "Active",
            "rank": "NA",
            "race": "White",
            "badge": "12345",
            "historic_badges": ["22", "33"],
            "historic_units": [
              {
                "id": 1,
                "unit_name": "001",
                "description": "Unit 001"
              },
              {
                "id": 2,
                "unit_name": "002",
                "description": "Unit 002"
              }
            ],
            "gender": "Male",
            "birth_year": 1951,
            "allegation_count": 90,
            "civilian_compliment_count": 0,
            "discipline_count": 0,
            "honorable_mention_count": 1,
            "honorable_mention_percentile": "88.777",
            "sustained_count": 4,
            "complaint_records": {
                "count": 27,
                "sustained_count": 0,
                "facets": [
                    {
                        "name": "category",
                        "entries": [
                            {
                                "name": "Illegal Search",
                                "count": 20,
                                "sustained_count": 0
                            },
                            {
                                "name": "Use of Force",
                                "count": 7,
                                "sustained_count": 0
                            }
                        ]
                    },
                    {
                        "name": "race"
                        "entries": [
                            {
                                "name": "White",
                                "count": 7,
                                "sustained_count": 0
                            },
                            {
                                "name": null,
                                "count": 20,
                                "sustained_count": 0
                            }
                        ]
                    },
                    {
                        "name": "age",
                        "entries": [
                            {
                                "name": "18",
                                "count": 20,
                                "sustained_count": 0
                            },
                            {
                                "name": "20",
                                "count": 7,
                                "sustained_count": 0
                            }
                        ]
                    },
                    {
                        "name": "gender",
                        "entries": [
                            {
                                "name": "Famale",
                                "count": 20,
                                "sustained_count": 0
                            },
                            {
                                "name": null,
                                "count": 7,
                                "sustained_count": 0
                            }
                        ]
                    }
                ]
            },
            "complaint_percentile": "58.446",
            "current_salary": 100000,
            "trr_count": 14,
            "major_award_count": 46,
            "complaint_records": {
                "count": 27,
                "sustained_count": 0,
                "facets": [
                    {
                        "name": "category",
                        "entries": [
                            {
                                "name": "Illegal Search",
                                "count": 20,
                                "sustained_count": 0
                            },
                            {
                                "name": "Use of Force",
                                "count": 7,
                                "sustained_count": 0
                            }
                        ]
                    },
                    {
                        "name": "race"
                        "entries": [
                            {
                                "name": "White",
                                "count": 7,
                                "sustained_count": 0
                            },
                            {
                                "name": null,
                                "count": 20,
                                "sustained_count": 0
                            }
                        ]
                    },
                    {
                        "name": "age",
                        "entries": [
                            {
                                "name": "18",
                                "count": 20,
                                "sustained_count": 0
                            },
                            {
                                "name": "20",
                                "count": 7,
                                "sustained_count": 0
                            }
                        ]
                    },
                    {
                        "name": "gender",
                        "entries": [
                            {
                                "name": "Famale",
                                "count": 20,
                                "sustained_count": 0
                            },
                            {
                                "name": null,
                                "count": 7,
                                "sustained_count": 0
                            }
                        ]
                    }
                ]
            },
            "percentiles": [
                {
                    "officer_id": 1,
                    "year": 2016,
                    "percentile_trr": "0.000",
                    "percentile_allegation": "76.282",
                    "percentile_allegation_civilian": "79.479",
                    "percentile_allegation_internal": "0.000"
                },
                {
                    "officer_id": 1,
                    "year": 2017,
                    "percentile_trr": "0.000",
                    "percentile_allegation": "58.446",
                    "percentile_allegation_civilian": "63.044",
                    "percentile_allegation_internal": "0.000"
                }
            ]
        }

## Officer timeline minimap [/officers/{officer_id}/timeline-minimap]

### Get Officer timeline minimap [GET]

+ Parameters
    + officer_id (number) - number ID of the officer

+ Response 200 (application/json)

        [
            {
                "kind": "cr",
                "year": 2016
            },
            {
                "kind": "trr",
                "year": 2015
            }
        ]

## Officer coaccusals [/officers/{officer_id}/coaccusals]

### Get Officer coaccusals [GET]

+ Parameters
    + officer_id (number) - number ID of the officer

+ Response 200 (application/json)

        {
            "id": "8562",
            "coaccusals": [
                {
                    "id": 1,
                    "full_name": "Officer 1",
                    "complaint_count": 2,
                    "sustained_count": 1,
                    "complaint_percentile": 94.0,
                    "race": "White",
                    "gender": "Male",
                    "birth_year": 1950,
                    "coaccusal_count": 2,
                    "rank": "Police Officer",
                    "percentile": {
                        "percentile_trr": "94.0000",
                        "percentile_allegation_internal": "95.0000",
                        "percentile_allegation_civilian": "91.0000",
                        "percentile_allegation": "94.0000",
                        "id": 1,
                        "year": 2016
                    }
                }, {
                    "id": 2,
                    "full_name": "Officer 2",
                    "complaint_count": 1,
                    "sustained_count": 1,
                    "complaint_percentile": 99.0,
                    "race": "Black",
                    "gender": "Male",
                    "birth_year": 1970,
                    "coaccusal_count": 1,
                    "rank": "Police Officer",
                    "percentile": {
                        "percentile_trr": "82.0000",
                        "percentile_allegation_internal": "71.0000",
                        "percentile_allegation_civilian": "98.0000",
                        "percentile_allegation": "95.0000",
                        "id": 2,
                        "year": 2016
                    }
                }
            ]
        }

## Officer timeline items list [/officers/{officer_id}/timeline-items/{?offset,limit}]

### Get Officer timeline items list [GET]

+ Parameters
    + officer_id (number) - number ID of the officer
    + offset (number, optional) - offset from which to get additional results
        + Default: `0`
    + limit (number, optional) - limit of how many results to return
        + Default: `20`

+ Response 200 (application/json)

        {
            "count": 20,
            "previous": null,
            "next": "http://cpdp.co/officers/123/timeline-items/?offset=20"
            "results": [
                {
                    "kind": "YEAR",
                    "crs": 2,
                    "year": 2016,
                    "trrs": 0,
                    "salary": 46492.96
                },
                {
                    "kind": "CR",
                    "crid": "307965",
                    "category": "Illegal Search",
                    "subcategory": "Search of premise/vehicle without warrant",
                    "finding": "Unfounded",
                    "coaccused": 4,
                    "date": "2016-08-24"
                },
                {
                    "kind": "UNIT_CHANGE",
                    "unit_name": "003",
                    "date": "2016-08-24"
                },
                {
                    "kind": "JOINED",
                    "date": "2012-08-24"
                }
            ]
        }

## Officer new timeline items list [/officers/{officer_id}/new-timeline-items]

### Get Officer new timeline items list [GET]

+ Parameters
    + officer_id (number) - number ID of the officer

+ Response 200 (application/json)

        [{
            "date": "2011-09-23",
            "kind": "FORCE",
            "taser": "true",
            "firearm_used": "false",
            "unit_name": "001",
            "rank": "Police Officer",
            "point": {
                "lon": 16.5,
                "lat": 67.8
            }
        }, {
            "date": "2011-08-23",
            "kind": "CR",
            "crid": "123456",
            "category": "category",
            "subcategory": "sub category",
            "finding": "Unfounded",
            "outcome": "Unknown",
            "coaccused": 4,
            "unit_name": "001",
            "rank": "Police Officer",
            "point": {
                "lon": 35.8,
                "lat": 76.8
            },
            "victims": [{
                "gender": "Male",
                "race": "White",
                "age": 34
            }, {
                "gender": "Female",
                "race": "Black",
                "age": 42
            }]
        }, {
            "date": "2011-03-23",
            "kind": "AWARD",
            "award_type": "Honorable Mention",
            "unit_name": "001",
            "rank": "Police Officer"
        }, {
            "date": "2010-01-01",
            "kind": "UNIT_CHANGE",
            "unit_name": "001",
            "rank": "Police Officer"
        }, {
            "date": "2000-01-01",
            "kind": "JOINED",
            "unit_name": "",
            "rank": "Police Officer"
        }]

## Top Officers by allegation [/officers/top-by-allegation/]

### List Officer Cards based on top 1% complaint percentile, sort by descending [GET]

+ Response 200 (application/json)

        [
            {
                "id": 8658,
                "visual_token_background_color": "#90b1f5",
                "full_name": "Corey Flagg",
                "complaint_count": 67,
                "sustained_count": 5,
                "birth_year": 1970,
                "complaint_percentile": 99.995,
                "race": "Black",
                "gender": "Male",
                "rank": "Police Officer",
                "percentile": {
                    "officer_id": 8658,
                    "year": 2017,
                    "percentile_trr": "0.000",
                    "percentile_allegation": "99.995",
                    "percentile_allegation_civilian": "99.990",
                    "percentile_allegation_internal": "99.795"
                }
            },
            {
                "id": 13788,
                "visual_token_background_color": "#90b1f5",
                "full_name": "Broderick Jones",
                "complaint_count": 69,
                "sustained_count": 8,
                "birth_year": 1971,
                "complaint_percentile": 99.99,
                "race": "Black",
                "gender": "Male",
                "rank": "Detective",
                "percentile": {
                    "officer_id": 13788,
                    "year": 2017,
                    "percentile_trr": "0.000",
                    "percentile_allegation": "99.990",
                    "percentile_allegation_civilian": "99.995",
                    "percentile_allegation_internal": "90.565"
                }
            }
        ]

## Officer create zip file [/officers/{officer_id}/create-zip-file/]

### Create zip file from excel and pdf files then save it on S3[GET]

+ Parameters
    + officer_id (number) - number ID of the officer

+ Response 200 (application/json)

## Officer request download [/officers/{officer_id}/request-download/{?with-docs}]

### Get the url to the officer zip file[GET]

+ Parameters
    + officer_id (number) - number ID of the officer
    + with-docs (string, optional) - should the zip file contain docs or not
        + Default: `false`

+ Response 200 (application/text)

        "https://officer-content-staging.s3.amazonaws.com/zip_with_docs/Officer_1_with_docs.zip"

## Officer Mobile [/mobile/officers/{officer_id}/]

### Get Officer Summary (include yearly percentiles) [GET]

+ Parameters
    + officer_id (number) - number ID of the officer

+ Response 200 (application/json)

        {
            "officer_id": 1,
            "full_name": "Robert Anderson",
            "percentiles": [
                {
                    "officer_id": 1,
                    "year": 2016,
                    "percentile_trr": "0.000",
                    "percentile_allegation": "76.282",
                    "percentile_allegation_civilian": "79.479",
                    "percentile_allegation_internal": "0.000"
                },
                {
                    "officer_id": 1,
                    "year": 2017,
                    "percentile_trr": "0.000",
                    "percentile_allegation": "58.446",
                    "percentile_allegation_civilian": "63.044",
                    "percentile_allegation_internal": "0.000"
                }
            ],
            "unit": {
              "unit_id": 2,
              "unit_name": "001",
              "description": "District 001"
            },
            "date_of_appt": "1992-01-02",
            "active": true,
            "rank": "Police Officer",
            "race": "White",
            "birth_year": 1965,
            "badge": "19675",
            "historic_badges": [
              "8137"
            ],
            "gender": "Male",
            "allegation_count": 125,
            "complaint_percentile": 99.892,
            "honorable_mention_count": 29,
            "sustained_count": 0,
            "discipline_count": 0,
            "civilian_compliment_count": 8,
            "trr_count": 24,
            "major_award_count": 0,
            "honorable_mention_percentile": 75.5604
        }

## TRR [/trr/{trr_id}/]

### Get TRR [GET]

+ Parameters
    + trr_id (number) - number ID of Use of Force Report

+ Response 200 (application/json)
        {
            "id": 781,
            "officer": {
                "id": 583,
                "full_name": "Robert Anderson",
                "gender": "Male",
                "race": "White",
                "rank": 'Detective',
                "appointed_date": "2000-10-10",
                "birth_year": 1973,
                "resignation_date": "2008-03-26",
                "unit": {
                    "unit_name": "253",
                    "description": "Targeted Response Unit"
                },
                "percentile_allegation_civilian": 92.7014,
                "percentile_allegation_internal": 0.0,
                "percentile_trr": 76.9689
            },
            "officer_in_uniform": true,
            "officer_assigned_beat": "4682E",
            "officer_on_duty": true,
            "subject_race": "BLACK",
            "subject_gender": "Male",
            "subject_age": 27,
            "force_category": "Other",
            "force_types": [
                "Physical Force - Stunning",
                "Verbal Commands",
                "Member Presence"
            ],
            "date_of_incident": "2004-04-23",
            "location_type": "Street",
            "address": "11XX 79Th St",
            "beat": 612,
            "point": {
                "lat": 41.7508596,
                "lng": -87.6533166
            }
        }

## TRR Documents [/trr/{trr_id}/request-document/]

### Request document [POST]

+ Parameters
    + trr_id (number) - number ID of TRR

+ Request (application/json)

        {
            "email": "asdf@example.com"
        }

+ Response 200 (application/json)

        {
            "trr_id": "293928",
            "message": "Thanks for subscribing"
        }

+ Request (application/json)

        {
            "email": "already_used@example.com"
        }

+ Response 200 (application/json)

        {
            "trr_id": "293928",
            "message": "Email already added"
        }

+ Request (application/json)

        {
            "email": "malformed email"
        }

+ Response 400 (application/json)

        {
            "message": "Please enter a valid email"
        }

## TRR Mobile [/mobile/trr/{trr_id}/]

### Get TRR [GET]

+ Parameters
    + trr_id (number) - number ID of Use of Force Report

+ Response 200 (application/json)
        {
            "id": 781,
            "officer": {
                "id": 583,
                "full_name": "Robert Anderson",
                "gender": "Male",
                "race": "White",
                "appointed_date": "2000-10-10",
                "birth_year": 1973,
                "resignation_date": "2008-03-26",
                "unit": {
                    "unit_name": "253",
                    "description": "Targeted Response Unit"
                },
                "percentile_allegation_civilian": 92.7014,
                "percentile_allegation_internal": 0.0,
                "percentile_trr": 76.9689
            },
            "officer_in_uniform": true,
            "officer_assigned_beat": "4682E",
            "officer_on_duty": true,
            "subject_race": "BLACK",
            "subject_gender": "Male",
            "subject_age": 27,
            "force_category": "Other",
            "force_types": [
                "Physical Force - Stunning",
                "Verbal Commands",
                "Member Presence"
            ],
            "date_of_incident": "2004-04-23",
            "location_type": "Street",
            "address": "11XX 79Th St",
            "beat": 612,
            "point": {
                "lat": 41.7508596,
                "lng": -87.6533166
            }
        }

## Mobile TRR Documents [/mobile/trr/{trr_id}/request-document/]

### Request document [POST]

+ Parameters
    + trr_id (number) - number ID of TRR

+ Request (application/json)

        {
            "email": "asdf@example.com"
        }

+ Response 200 (application/json)

        {
            "trr_id": "293928",
            "message": "Thanks for subscribing"
        }

+ Request (application/json)

        {
            "email": "already_used@example.com"
        }

+ Response 200 (application/json)

        {
            "trr_id": "293928",
            "message": "Email already added"
        }

+ Request (application/json)

        {
            "email": "malformed email"
        }

+ Response 400 (application/json)

        {
            "message": "Please enter a valid email"
        }

## Complaint summaries [/cr/complaint-summaries/]

### List recent updated Summary of CR [GET]

+ Response 200 (application/json)

        [
            {
                "crid": "1080158",
                "category_names": [
                    "Unknown"
                ],
                "incident_date": "2016-04-18",
                "summary": "Officer A was off-duty and inside her residence when she reportedly ..."
            },
            {
                "crid": "1079959",
                "category_names": [
                    "Unknown"
                ],
                "incident_date": "2016-04-05",
                "summary": "Subject and the off-duty Officer A had a motor vehicle accident in which Subject ..."
            }
        ]

## CR [/mobile/cr/{crid}/]

### Get CR [GET]

+ Parameters
    + crid (number) - number ID of Allegation

+ Response 200 (application/json)

        {
            "crid": "12345",
            'most_common_category': {
                'category': 'Operation/Personnel Violations',
                'allegation_name': 'NEGLECT OF DUTY/CONDUCT UNBECOMING - ON DUTY'
            },
            "coaccused": [
                {
                    "id": 123,
                    "full_name": "Robert O'Niell",
                    "final_outcome": "Reprimand",
                    "final_finding": "Sustained",
                    "race": "Asian",
                    "gender": "Male",
                    "rank": "Police Officer",
                    "birth_year": "1975",
                    "complaint_percentile": 99.861,
                    "category": "Operation/Personnel Violations",
                    "percentile": {
                        "percentile_allegation": "99.8610",
                        "percentile_allegation_civilian": "99.8810",
                        "percentile_allegation_internal": "80.5690",
                        "percentile_trr": "92.1100",
                        "id": 123,
                        "year": 2016
                    }
                },
                {
                    "id": 456,
                    "full_name": "Alex Foo",
                    "final_outcome": "Unknown",
                    "final_finding": "Sustained",
                    "race": "White",
                    "gender": "Male",
                    "rank": "Detective",
                    "birth_year": "1980",
                    "complaint_percentile": 92.764,
                    "category": "Operation/Personnel Violations",
                    "percentile": {
                        "percentile_allegation": "99.8610",
                        "percentile_allegation_civilian": "99.8810",
                        "percentile_allegation_internal": "80.5690",
                        "percentile_trr": "92.1100",
                        "id": 456,
                        "year": 2016
                    }
                }
            ],
            "complainants": [
                {
                    "race": "White",
                    "gender": "Male",
                    "age": 18
                },
                {
                    "race": "Black",
                    "gender": "Female",
                    "age": 20
                }
            ],
            "victims": [
                {
                    "race": "Black",
                    "gender": "Male",
                    "age": 53
                },
                {
                    "race": "Black",
                    "gender": "Female",
                    "age": 20
                }
            ],
            "summary": "Lorem ipsum dolor.",
            "point": {
                "lon": -87.664606,
                "lat": 41.68731
            },
            "incident_date": "2002-02-28",
            "start_date": "2002-02-30",
            "end_date": "2002-04-21",
            "address": "3510 Michigan Ave, Chicago, IL 60653",
            "location": "Police Building",
            "beat": "23",
            "involvements": [
                {
                    "officer_id": 1,
                    "involved_type": "investigator",
                    "full_name": "Lauren Skol",
                    "badge": "CPD",
                    "percentile_allegation_civilian": 99.881,
                    "percentile_allegation_internal": 80.569,
                    "percentile_trr": 92.110
                },
                {
                    "officer_id": 2,
                    "involved_type": "police_witness",
                    "full_name": "Raymond Piwinicki",
                    "allegation_count": 10,
                    "sustained_count": 3,
                    "percentile_allegation_civilian": 99.881,
                    "percentile_allegation_internal": 80.569,
                    "percentile_trr": 92.110
                },
                {
                    "officer_id": 3,
                    "involved_type": "police_witness",
                    "full_name": "German Felix",
                    "allegation_count": 10,
                    "sustained_count": 3,
                    "percentile_allegation_civilian": 99.881,
                    "percentile_allegation_internal": 80.569,
                    "percentile_trr": 92.110
                }
            ],
            "attachments": [
                {
                    "title": "CHI - R-00001275 Red",
                    "file_type": "video",
                    "url": "http://foo.com",
                    "preview_image_url": "http://foo.com/bar.jpg"
                },
                {
                    "title": "CHI - R-00001275 Red",
                    "file_type": "audio",
                    "url": "http://foo.com",
                    "preview_image_url": "http://foo.com/bar.jpg"
                },
                {
                    "title": "CHI - R-00001275 Red",
                    "file_type": "document",
                    "url": "http://foo.com",
                    "preview_image_url": "http://foo.com/bar.jpg"
                }
            ]
        }

## CR Mobile Documents [/mobile/cr/{crid}/request-document/]

### Request document [POST]

+ Parameters
    + crid (number) - number ID of Allegation

+ Request (application/json)

        {
            "email": "asdf@example.com"
        }

+ Response 200 (application/json)

        {
            "crid": "293928",
            "message": "Thanks for subscribing"
        }

+ Request (application/json)

        {
            "email": "already_used@example.com"
        }

+ Response 200 (application/json)

        {
            "crid": "293928",
            "message": "Email already added"
        }

+ Request (application/json)

        {
            "email": "malformed email"
        }

+ Response 400 (application/json)

        {
            "message": "Please enter a valid email"
        }

## CR [/cr/{crid}/]

### Get CR [GET]

+ Parameters
    + crid (number) - number ID of Allegation

+ Response 200 (application/json)

        {
            "crid": "12345",
            'most_common_category': {
                'category': 'Operation/Personnel Violations',
                'allegation_name': 'NEGLECT OF DUTY/CONDUCT UNBECOMING - ON DUTY'
            },
            "coaccused": [
                {
                    "id": 123,
                    "full_name": "Robert O'Niell",
                    "gender": "Male",
                    "race": "White",
                    "birth_year": 1975,
                    "complaint_count": 43,
                    "sustained_count": 1,
                    "final_outcome": "Reprimand",
                    "final_finding": "Sustained",
                    "recommended_outcome": "10 Day Suspension",
                    "category": "Operation/Personnel Violations",
                    "complaint_percentile": 99.861,
                    "percentile": {
                        "percentile_allegation": "99.8610",
                        "percentile_allegation_civilian": "99.8810",
                        "percentile_allegation_internal": "80.5690",
                        "percentile_trr": "92.1100",
                        "id": 123,
                        "year": 2016
                    }
                },
                {
                    "id": 456,
                    "full_name": "Alex Foo",
                    "gender": "Male",
                    "race": "Black",
                    "birth_year": 1980,
                    "complaint_count": 23,
                    "sustained_count": 0,
                    "final_outcome": "Unknown",
                    "final_finding": "Sustained",
                    "category": "Operation/Personnel Violations",
                    "complaint_percentile": 99.861,
                    "percentile": {
                        "percentile_allegation": "99.8610",
                        "percentile_allegation_civilian": "99.8810",
                        "percentile_allegation_internal": "80.5690",
                        "percentile_trr": "92.1100",
                        "id": 456,
                        "year": 2016
                    }
                }
            ],
            "complainants": [
                {
                    "race": "White",
                    "gender": "Male",
                    "age": 18
                },
                {
                    "race": "Black",
                    "gender": "Female",
                    "age": 20
                }
            ],
            "victims": [
                {
                    "race": "Black",
                    "gender": "Male",
                    "age": 53
                },
                {
                    "race": "Black",
                    "gender": "Female",
                    "age": 20
                }
            ],
            "summary": "Lorem ipsum dolor.",
            "point": {
                "lon": -87.664606,
                "lat": 41.68731
            },
            "incident_date": "2002-02-28",
            "start_date": "2002-02-30",
            "end_date": "2002-04-21",
            "address": "3510 Michigan Ave, Chicago, IL 60653",
            "location": "Police Building",
            "beat": "23",
            "involvements": [
                {
                    "officer_id": 1,
                    "involved_type": "investigator",
                    "full_name": "Lauren Skol",
                    "badge": "CPD",
                    "percentile_allegation_civilian": 99.881,
                    "percentile_allegation_internal": 80.569,
                    "percentile_trr": 92.110
                },
                {
                    "officer_id": 2,
                    "involved_type": "police_witness",
                    "full_name": "Raymond Piwinicki",
                    "allegation_count": 10,
                    "sustained_count": 3,
                    "percentile_allegation_civilian": 99.881,
                    "percentile_allegation_internal": 80.569,
                    "percentile_trr": 92.110
                },
                {
                    "officer_id": 3,
                    "involved_type": "police_witness",
                    "full_name": "German Felix",
                    "allegation_count": 10,
                    "sustained_count": 3,
                    "percentile_allegation_civilian": 99.881,
                    "percentile_allegation_internal": 80.569,
                    "percentile_trr": 92.110
                }
            ],
            "attachments": [
                {
                    "title": "CHI - R-00001275 Red",
                    "file_type": "video",
                    "url": "http://foo.com",
                    "preview_image_url": "http://foo.com/bar.jpg"
                },
                {
                    "title": "CHI - R-00001275 Red",
                    "file_type": "audio",
                    "url": "http://foo.com",
                    "preview_image_url": "http://foo.com/bar.jpg"
                },
                {
                    "title": "CHI - R-00001275 Red",
                    "file_type": "document",
                    "url": "http://foo.com",
                    "preview_image_url": "http://foo.com/bar.jpg"
                }
            ]
        }

## Related Complaints [/cr/{crid}/related-complaints/{?match,distance,offset,limit}]

### Get related complaints [GET]

+ Parameters
    + crid (number, required) - number ID of Allegation
    + match (enum[string], required) - whether the related complaints have similar categories or similar officers
        + Members
            + `categories`
            + `officers`
    + distance (enum[string], required) - distance from where this incident happen
        + Members
            + `0.5mi`
            + `1mi`
            + `2.5mi`
            + `5mi`
            + `10mi`
    + offset (number, optional) - offset from which to get additional results
        + Default: `0`
    + limit (number, optional) - limit of how many results to return
        + Default: `20`

+ Response 200 (application/json)

        {
            "count": 1,
            "previous": null,
            "next": null
            "results": [
                {
                    "crid": "838409",
                    "complainants": [{
                        "race": "White",
                        "gender": "Male",
                        "age": 18
                    }],
                    "coaccused": [
                        "R. Piwnicki",
                        "T. Parker"
                    ],
                    "category_names": [
                        "False Arrest",
                        "Use Of Force"
                    ],
                    "point": {
                        "lat": 84.343,
                        "lon": 1.3434
                    }
                }
            ]
        }

## Search Aliases [/aliases/{aliasType}/{id}/]

### Update search aliases for a search result [POST]

+ Parameters
    + aliasType (string) - Can be officer/neighborhood/community/report/unit
    + id (number) - Primary key of search result

+ Request (application/json)

        {
            aliases: ["foo", "bar"]
        }

+ Response 200 (application/json)

        {
            "message": "Aliases successfully updated",
            "aliases": ["foo", "bar"]
        }

+ Request (application/json)

        {
            aliases: ["an alias that is absolutely way too long"]
        }

+ Response 400 (application/json)

        {
            "message": {
                "aliases": ["Ensure this field has no more than 20 characters."]
            }
        }

## CR Documents [/cr/{crid}/request-document/]

### Request document [POST]

+ Parameters
    + crid (number) - number ID of Allegation

+ Request (application/json)

        {
            "email": "asdf@example.com"
        }

+ Response 200 (application/json)

        {
            "crid": "293928",
            "message": "Thanks for subscribing"
        }

+ Request (application/json)

        {
            "email": "already_used@example.com"
        }

+ Response 200 (application/json)

        {
            "crid": "293928",
            "message": "Email already added"
        }

+ Request (application/json)

        {
            "email": "malformed email"
        }

+ Response 400 (application/json)

        {
            "message": "Please enter a valid email"
        }

## CR new documents [/cr/list-by-new-document]

### List document which has new documents (in document-cloud) [GET]

+ Parameters
    + limit (number) - number of allegations which has new document

+ Response 200 (application/json)
        [
            {
                "crid": "111",
                "latest_document": {
                    "title": "CR document 1",
                    "url": "http://cr-document.com/1",
                    "preview_image_url": "http://preview.com/url"
                },
                "num_recent_documents": 2
            },
            {
                "crid": "112",
                "latest_document": {
                    "title": "CR document 3",
                    "url": "http://cr-document.com/3",
                    "preview_image_url": "http://preview.com/url3"
                },
                "num_recent_documents": 1
            },
        ]

## Unit summary [/units/{unit_id}/summary]

### Get Unit Summary [GET]

+ Parameters
    + unit_id (number) - number ID of the unit

+ Response 200 (application/json)

        {
            "unit_name": "001",
            "member_records": {
                "active_members": 72,
                "total": 156,
                "facets": [
                    {
                        "name": "race",
                        "entries": [
                            {
                                "name": "White",
                                "count": 10
                            },
                            {
                                "name": "Unknown",
                                "count": 1
                            }
                        ]
                    },
                    {
                        "name": "age",
                        "entries": [
                            {
                                "name": "21-30",
                                "count": 10
                            },
                            {
                                "name": "51+",
                                "count": 2
                            }
                        ]
                    },
                    {
                        "name": "gender",
                        "entries": [
                            {
                                "name": "Male",
                                "count": 10
                            },
                            {
                                "name": "Female",
                                "count": 6
                            },
                            {
                                "name": "X",
                                "count": 4
                            },
                            {
                                "name": "Unknown",
                                "count": 2
                            }
                        ]
                    }
                ]
            },
            "complaint_records": {
                "count": 27,
                "sustained_count": 3,
                "facets": [
                    {
                        "name": "category",
                        "entries": [
                            {
                                "name": "Illegal Search",
                                "count": 12,
                                "sustained_count": 2
                            }
                        ]
                    },
                    {
                        "name": "race"
                        "entries": [
                            {
                                "name": "White",
                                "count": 9,
                                "sustained_count": 1
                            }
                        ]
                    },
                    {
                        "name": "age",
                        "entries": [
                            {
                                "name": "21-30",
                                "count": 5,
                                "sustained_count": 0
                            }
                        ]
                    },
                    {
                        "name": "gender",
                        "entries": [
                            {
                                "name": "Female",
                                "count": 2,
                                "sustained_count": 0
                            }
                        ]
                    }
                ]
            }
        }

## Activity grid [/activity-grid/]

### Get activity cards [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "full_name": "Jerome Finnigan",
                "visual_token_background_color": "#90b1f5",
                "birth_year": 1963,
                "complaint_count": 90,
                "complaint_percentile": 88.55,
                "gender": "Male",
                "rank": "Police Officer",
                "race": "White",
                "sustained_count": 4,
                "percentile": {
                    "officer_id": 5193,
                    "year": 2017,
                    "percentile_trr": "91.696",
                    "percentile_allegation": "99.870",
                    "percentile_allegation_civilian": "99.895",
                    "percentile_allegation_internal": "80.494"
                }
            },
            {
                "id": 2,
                "full_name": "Raymond Piwnicki",
                "visual_token_background_color": "#aec9e8",
                "birth_year": 1963,
                "complaint_count": 89,
                "complaint_percentile": None,
                "gender": "Male",
                "rank": "Detective",
                "race": "White",
                "sustained_count": 6,
                "percentile": {
                    "officer_id": 5193,
                    "year": 2017,
                    "percentile_trr": "91.696",
                    "percentile_allegation": "99.870",
                    "percentile_allegation_civilian": "99.895",
                    "percentile_allegation_internal": "80.494"
                }
            }
        ]

## Search term categories list [/search-term-categories/]

### Get Search term categories [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Geography",
                "items": [
                    {
                        "name": "Police Districts",
                        "description": "A form of division of a geographical area patrolled by a police force",
                        "id": "police-districts",
                        "call_to_action_type": "view_all"
                    }
                ]
            },
            {
                "name": "Officers",
                "items": [
                    {
                        "name": "Officer Name",
                        "description": "Type the name of an officer into the search bar",
                        "id": "officer-name",
                        "call_to_action_type": "plain_text"
                    }
                ]
            },
            {
                "name": "Complaint Categories",
                "items": [
                    {
                        "name": "Conduct Unbecoming",
                        "description": "Search the data tool for Conduct Unbecoming",
                        "id": "conduct-unbecoming",
                        "call_to_action_type": "link",
                        "link": "https://data.cpdp.co/url-mediator/session-builder?cat__category=Conduct%20Unbecoming"
                    }
                ]
            }
        ]

## General search [/v1/suggestion/{term}/?limit={limit}]

+ Parameters
    + term (string) - Search term
    + limit (number) - Django REST framework limit pagination

### Get search results [GET]

+ Response 200 (application/json)

        {
          "NEIGHBORHOOD": [
            {
              "name": "Washington Heights",
              "tags": ["neighborhoods"],
              "url": "https://data.cpdp.co/url-mediator/session-builder?neighborhood=Washington Heights",
              "most_common_complaint": [
                {
                  "count": 104,
                  "id": 204,
                  "name": "Operation/Personnel Violations"
                },
                {
                  "count": 66,
                  "id": 98,
                  "name": "Use Of Force"
                },
                {
                  "count": 53,
                  "id": 71,
                  "name": "Illegal Search"
                }
              ],
              "officers_most_complaint": [
                {
                  "count": 16,
                  "id": 32344,
                  "name": "Brandon Smith"
                },
                {
                  "count": 15,
                  "id": 7199,
                  "name": "Richard Doroniuk"
                },
                {
                  "count": 15,
                  "id": 9115,
                  "name": "Freddie Frazier"
                }
              ],
              "allegation_count": 1081,
              "id": "345"
            },
            {
              "name": "Washington Park",
              "tags": ["neighborhoods"],
              "url": "https://data.cpdp.co/url-mediator/session-builder?neighborhood=Washington Park",
              "most_common_complaint": [
                {
                  "count": 99,
                  "id": 204,
                  "name": "Operation/Personnel Violations"
                },
                {
                  "count": 78,
                  "id": 98,
                  "name": "Use Of Force"
                },
                {
                  "count": 39,
                  "id": 194,
                  "name": "Operation/Personnel Violations"
                }
              ],
              "officers_most_complaint": [
                {
                  "count": 9,
                  "id": 10259,
                  "name": "Daniel Gomez"
                },
                {
                  "count": 9,
                  "id": 32154,
                  "name": "Pablo Mariano"
                },
                {
                  "count": 7,
                  "id": 966,
                  "name": "Stephen Austin"
                }
              ],
              "allegation_count": 903,
              "id": "339"
            }
          ],
          "CO-ACCUSED": [
            {
              "to": "/officer/28416/henry-thomas/",
              "result_extra_information": "Badge # 20455",
              "result_reason": "coaccused with Walter Ware (17626)",
              "id": "AV_JHHFVEEvAIPTOfirI"
            },
            {
              "to": "/officer/32306/geno-rouse/",
              "result_extra_information": "Badge # 2155",
              "result_reason": "coaccused with Walter Ware (17626)",
              "id": "AV_JHHFfEEvAIPTOfirL"
            },
          ],
          "COMMUNITY": [
            {
              "median_income": "$43,990",
              "tags": [ "community" ],
              "allegation_count": 1081,
              "most_common_complaint": [
                {
                  "count": 104,
                  "id": 204,
                  "name": "Operation/Personnel Violations"
                },
                {
                  "count": 66,
                  "id": 98,
                  "name": "Use Of Force"
                },
                {
                  "count": 53,
                  "id": 71,
                  "name": "Illegal Search"
                }
              ],
              "officers_most_complaint": [
                {
                  "count": 16,
                  "id": 32344,
                  "name": "Brandon Smith"
                },
                {
                  "count": 15,
                  "id": 7199,
                  "name": "Richard Doroniuk"
                },
                {
                  "count": 15,
                  "id": 9115,
                  "name": "Freddie Frazier"
                }
              ],
              "name": "Washington Heights",
              "url": "https://data.cpdp.co/url-mediator/session-builder?community=Washington Heights",
              "race_count": [
                {
                  "count": 25968,
                  "race": "Black or African-American"
                },
                {
                  "count": 510,
                  "race": "Other"
                },
                {
                  "count": 351,
                  "race": "White"
                },
                {
                  "count": 287,
                  "race": "Persons of Spanish Language"
                },
                {
                  "count": 0,
                  "race": "Asian"
                }
              ],
              "id": "497"
            },
            {
              "median_income": "$21,869",
              "tags": [ "community" ],
              "allegation_count": 903,
              "most_common_complaint": [
                {
                  "count": 99,
                  "id": 204,
                  "name": "Operation/Personnel Violations"
                },
                {
                  "count": 78,
                  "id": 98,
                  "name": "Use Of Force"
                },
                {
                  "count": 39,
                  "id": 194,
                  "name": "Operation/Personnel Violations"
                }
              ],
              "officers_most_complaint": [
                {
                  "count": 9,
                  "id": 10259,
                  "name": "Daniel Gomez"
                },
                {
                  "count": 9,
                  "id": 32154,
                  "name": "Pablo Mariano"
                },
                {
                  "count": 7,
                  "id": 966,
                  "name": "Stephen Austin"
                }
              ],
              "name": "Washington Park",
              "url": "https://data.cpdp.co/url-mediator/session-builder?community=Washington Park",
              "race_count": [
                {
                  "count": 11595,
                  "race": "Black or African-American"
                },
                {
                  "count": 271,
                  "race": "Other"
                },
                {
                  "count": 158,
                  "race": "Persons of Spanish Language"
                },
                {
                  "count": 48,
                  "race": "White"
                },
                {
                  "count": 9,
                  "race": "Asian"
                }
              ],
              "id": "432"
            }
          ],
          "UNIT": [{
            "tags": [ ],
            "name": "001",
            "description": "District 001",
            "to": "/unit/001/",
            "id": "2"
          }],
          "UNIT > OFFICERS": [{
            "name": "Robert Bullington",
            "to": "/officer/3277/robert-bullington/",
            "tags": [ ],
            "birth_year": 1963,
            "race": "White",
            "gender": "Male",
            "badge": "8684",
            "rank": "Police Officer",
            "unit": {
              "unit_name": "001",
              "description": "District 001",
              "id": 2,
              "long_unit_name": "Unit 001"
            },
            "appointed_date": "1988-11-07",
            "resignation_date": null,
            "allegation_count": 79,
            "sustained_count": 2,
            "trr_count": 0,
            "discipline_count": 1,
            "honorable_mention_count": 13,
            "civilian_compliment_count": 10,
            "major_award_count": 0,
            "honorable_mention_percentile": 63.7869,
            "percentiles": [{
              "percentile_allegation_civilian": "98.5779",
              "year": 2000,
              "id": 3277,
              "percentile_allegation_internal": "0.0000",
              "percentile_allegation": "98.9364"
            }, {
              "percentile_allegation_civilian": "98.8863",
              "year": 2001,
              "id": 3277,
              "percentile_allegation_internal": "0.0000",
              "percentile_allegation": "99.0767"
            }],
            "id": "3277"
          }],
          "OFFICER": [
            {
              "visual_token_background_color": "#90b1f5",
              "result_extra_information": "Badge # 2328",
              "rank": "Sergeant Of Police",
              "sex": "Male",
              "result_reason": "",
              "unit": "005",
              "salary": null,
              "tags": [],
              "to": "/officer/29841/tommy-walker/",
              "race": "Black",
              "id": "29841"
            },
            {
              "visual_token_background_color": "#90b1f5",
              "result_extra_information": "Badge # 1730",
              "rank": "Sergeant Of Police",
              "sex": "Male",
              "result_reason": "",
              "unit": "008",
              "salary": null,
              "tags": [],
              "to": "/officer/29833/corey-walker/",
              "race": "Black",
              "id": "29833"
            },
          ],
          "RANK": [{
            "id": "Chief",
            "name": "Chief",
            "active_officers_count": 12,
            "officers_most_complaints": [{
              "id": 123,
              "name": "John Hollowell",
              "count": 11,
              "percentile_allegation": "76.2821",
              "percentile_allegation_civilian": "79.4791",
              "percentile_allegation_internal": "0.0001"
              "percentile_trr": "99.0001"
            }]
          }]
        }

## Specific type search [/v1/suggestion/{term}/single/{?contentType,offset,limit}]

+ Parameters
    + term (string) - Search term
    + contentType (string) - Data content type (OFFICER, UNIT, COMMUNITY, NEIGHBORHOOD, CO-ACCUSED, UNIT > OFFICERS)
    + offset (number, optional) - offset from which to get additional results
        + Default: `0`
    + limit (number, optional) - limit of how many results to return
        + Default: `20`

### Get search results [GET]

+ Response 200 (application/json)

        {
          "count": 2,
          "previous": null,
          "next": null,
          "results": [
            {
              "text": "Orson Ward",
              "payload": {
                "visual_token_background_color": "#c6d4ec",
                "result_extra_information": "Badge # 13603",
                "rank": "Police Officer",
                "sex": "Male",
                "result_reason": "",
                "unit": "010",
                "salary": null,
                "result_text": "Orson Ward",
                "tags": [],
                "to": "/officer/30022/orson-ward/",
                "race": "Black"
              },
              "id": "30022"
            },
            {
              "text": "Orson Kallenback",
              "payload": {
                "visual_token_background_color": "#f5f4f4",
                "result_extra_information": "",
                "rank": "Police Officer",
                "sex": "Male",
                "result_reason": "",
                "unit": "169",
                "salary": null,
                "result_text": "Orson Kallenback",
                "tags": [],
                "to": "/officer/14026/orson-kallenback/",
                "race": "White"
              },
              "id": "14026"
            }
          ]
        }

## City Summary [/v2/city-summary/]

### Get city summary [GET]

+ Response 200 (application/json)

        {
            "allegation_count": 125735,
            "most_common_complaints": [
                {
                    "name": "Operation/Personnel Violations",
                    "count": 1
                },
                {
                    "name": "Use Of Force",
                    "count": 1
                },
                {
                    "name": "Illegal Search",
                    "count": 1
                },
            ],
            "discipline_count": 6404
        }

## Popup [/v2/popup/]

### Get popup [GET]

+ Response 200 (application/json)

         [
            {
                "name": "unit",
                "page": "officer",
                "title": "Unit",
                "text": "To be updated later"
            },
            {
                "name": "rank",
                "page": "officer",
                "title": "Rank",
                "text": "To be updated later"
            },
            {
                "name": "investigator",
                "page": "complaint",
                "title": "Investigator",
                "text": "To be updated later"
            }
         ]

## Attachment [/attachment/]

### Get attachments [GET]

+ Response 200 (application/json)

        {
            "count": 2,
            "next": "http://testserver/api/v2/attachment/?limit=2&offset=2",
            "previous": None,
            "results": [
                {
                    "id": 4677,
                    "created_at": "2017-01-14T06:00:01-06:00",
                    "title": "CRID 1051117 CR",
                    "source_type": "DOCUMENTCLOUD",
                    "preview_image_url": "https://assets.documentcloud.org/documents/4769596/pages/CRID-1051117-CR-p1-normal.gif",
                },
                {
                    "id": 4829,
                    "created_at": "2017-01-14T06:00:01-06:00",
                    "title": "CRID 1064593 CR",
                    "source_type": "DOCUMENTCLOUD",
                    "preview_image_url": "https://assets.documentcloud.org/documents/4769386/pages/CRID-1064593-CR-p1-normal.gif",
                }
            ]
        }
