# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 10:37
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
    ]
