# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_add_faqpage_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
