# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-13 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('faq', '0007_delete_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='faqpagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='faqpagetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='faqspage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='FAQPage',
        ),
        migrations.DeleteModel(
            name='FAQPageTag',
        ),
        migrations.DeleteModel(
            name='FAQsPage',
        ),
    ]
