# Generated by Django 2.2.10 on 2020-08-10 08:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuit',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
