# Generated by Django 2.2.10 on 2020-08-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0002_lawsuit_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuit',
            name='primary_cause',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
