# Generated by Django 2.2.10 on 2020-08-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0005_add_cache_columns_to_lawsuits'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuit',
            name='total_payments',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
    ]
