# Generated by Django 2.2.10 on 2020-08-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0006_lawsuit_total_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawsuit',
            name='officers',
            field=models.ManyToManyField(related_name='lawsuits', to='data.Officer'),
        ),
    ]
