# Generated by Django 2.2.10 on 2020-08-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0007_alter_officers_fields_in_lawsuits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawsuit',
            name='total_legal_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='total_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='total_settlement',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='legal_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='settlement',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
