# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-15 07:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('target_model', models.CharField(max_length=255)),
                ('log_type', models.IntegerField(choices=[(1, b'Create'), (2, b'Update'), (3, b'Delete')])),
                ('object_pk', models.IntegerField(null=True)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('source', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
