# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-07 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_event_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('usages', models.PositiveIntegerField(default=0)),
                ('results', models.PositiveIntegerField(default=0)),
                ('query_type', models.CharField(choices=[[b'free_text', b'Free Text'], [b'no_interaction', b'No Interaction']], max_length=20)),
                ('last_entered', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
