# Generated by Django 2.1.3 on 2018-11-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_searchtracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtracking',
            name='query_type',
            field=models.CharField(choices=[['free_text', 'Free Text'], ['no_interaction', 'No Interaction']], max_length=20),
        ),
    ]
