# Generated by Django 2.1.3 on 2019-02-11 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0110_merge_20190108_0253'),
        ('analytics', '0005_add_created_at_and_updated_at_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_from_page', models.CharField(max_length=50)),
                ('app', models.CharField(max_length=50)),
                ('attachment_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.AttachmentFile')),
            ],
        ),
    ]
