# Generated by Django 2.1.3 on 2019-02-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_create_attachmenttracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmenttracking',
            name='kind',
            field=models.CharField(choices=[('DOWNLOAD_EVENT_TYPE', 'Download Event Type'), ('VIEW_EVENT_TYPE', 'View Event Type')], default='VIEW_EVENT_TYPE', max_length=50),
        ),
        migrations.AlterField(
            model_name='attachmenttracking',
            name='accessed_from_page',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='attachmenttracking',
            name='app',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
