ADD_TAG_TO_DOCUMENT = 'ADD_TAG_TO_DOCUMENT'
REMOVE_TAG_FROM_DOCUMENT = 'REMOVE_TAG_FROM_DOCUMENT'

ACTION_TYPE_CHOICES = (
    (ADD_TAG_TO_DOCUMENT, 'Add tag to document'),
    (REMOVE_TAG_FROM_DOCUMENT, 'Remove tag from document'),
)
