# Generated by Django 2.2.10 on 2020-05-04 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0003_create_initial_visual_token_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualtokencolor',
            name='lower_range',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='visualtokencolor',
            name='upper_range',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
