FREE_TEXT = 'free_text'
NO_INTERACTION = 'no_interaction'

QUERY_TYPES = [
    [FREE_TEXT, 'Free Text'],
    [NO_INTERACTION, 'No Interaction']
]

DOWNLOAD_EVENT_TYPE = 'DOWNLOAD_EVENT_TYPE'
VIEW_EVENT_TYPE = 'VIEW_EVENT_TYPE'

ATTACHMENT_FILE_TRACKING_EVENT_TYPE = (
    (DOWNLOAD_EVENT_TYPE, 'Download Event Type'),
    (VIEW_EVENT_TYPE, 'View Event Type')
)
