# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 08:03
from __future__ import unicode_literals

from django.core.management import BaseCommand
from django.contrib.contenttypes.models import ContentType

from tqdm import tqdm
from wagtail.wagtailcore.models import Page

from story.models import CoveragePage, StoryPage, Story


class Command(BaseCommand):
    def handle(self, *args, **options):
        root_page = Page.objects.get(pk=1)
        coverage_page = root_page.add_child(
            instance=CoveragePage(
                title='Coverage', slug='coverage', content_type=ContentType.objects.get_for_model(CoveragePage)
            ))

        for story in tqdm(Story.objects.all(), desc='Create stories'):
            coverage_page.add_child(instance=StoryPage(
                content_type=ContentType.objects.get_for_model(StoryPage),
                title=story.title,
                publication_name=story.newspaper.name,
                publication_short_url=story.newspaper.short_name,
                canonical_url=story.canonical_url,
                publication_date=story.post_date,
                image=story.image,
                body=story.body))
