IDS_OF_OTHER_BOTS = [30582622, 4880788160, 4923697764]
TWITTER_ACTIVITY_API = 'https://api.twitter.com/1.1/account_activity/all/'

RESPONSE_TYPE_SINGLE_OFFICER = 'single_officer'
RESPONSE_TYPE_COACCUSED_PAIR = 'coaccused_pair'
RESPONSE_TYPE_NOT_FOUND = 'not_found'
RESPONSE_TYPE_CHOICES = [
    [RESPONSE_TYPE_SINGLE_OFFICER, 'Single Officer'],
    [RESPONSE_TYPE_COACCUSED_PAIR, 'Coaccused Pair'],
    [RESPONSE_TYPE_NOT_FOUND, 'Not Found']
]
