# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-31 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('story', '0005_add_story_model'),
        ('wagtailcore', '0028_merge'),
        ('faq', '0003_add_faq_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('faq1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page1', to='faq.FAQ')),
                ('faq2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page2', to='faq.FAQ')),
                ('faq3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page3', to='faq.FAQ')),
                ('report1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page1', to='story.Story')),
                ('report2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page2', to='story.Story')),
                ('report3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page3', to='story.Story')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
