# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('story', '0005_reportingpage'),
        ('wagtailcore', '0028_merge'),
        ('faq', '0003_faqspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('faqs', models.ManyToManyField(to='faq.FAQPage')),
                ('stories', models.ManyToManyField(to='story.StoryPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
