# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-05 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_complaints_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_use_of_force_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='page_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='vftg_content',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='vftg_header',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='faq1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page1', to='faq.FAQ'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='faq2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page2', to='faq.FAQ'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='faq3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page3', to='faq.FAQ'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='report1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page1', to='story.Story'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='report2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page2', to='story.Story'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='report3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page3', to='story.Story'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='vftg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='vftg_link',
            field=models.URLField(blank=True),
        ),
    ]
