# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_alter_landing_page_add_custom_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='keywords',
        ),
    ]
