# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_remove_landingpage_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='coverage_pool_size',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='coverage_pool_strategy',
            field=models.CharField(choices=[(b'LAST_N_DAYS', b'last n days (n is defined by coverage pool size)'), (b'LAST_N_ENTRIES', b'last n coverages (n is defined by coverage pool size)')], default=b'LAST_N_DAYS', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='faq_pool_size',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='faq_pool_strategy',
            field=models.CharField(choices=[(b'LAST_N_DAYS', b'last n days (n is defined by coverage pool size)'), (b'LAST_N_ENTRIES', b'last n coverages (n is defined by coverage pool size)')], default=b'LAST_N_DAYS', max_length=255),
        ),
    ]
