# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_add_randomizer_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingpage',
            old_name='coverage_pool_size',
            new_name='coverage_strat_n',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='faq_pool_size',
            new_name='faq_strat_n',
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='coverage_pool_strategy',
            field=models.CharField(choices=[(b'LAST_N_DAYS', b'last n days'), (b'LAST_N_ENTRIES', b'last n entries')], default=b'LAST_N_ENTRIES', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='faq_pool_strategy',
            field=models.CharField(choices=[(b'LAST_N_DAYS', b'last n days'), (b'LAST_N_ENTRIES', b'last n entries')], default=b'LAST_N_ENTRIES', max_length=255),
        ),
    ]
