# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_auto_20160829_2232'),
        ('story', '0008_migrate_data_from_storypage_to_story'),
        ('landing_page', '0004_auto_20160829_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='faqs',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='stories',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='faq1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page1', to='faq.FAQ'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='faq2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page2', to='faq.FAQ'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='faq3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page3', to='faq.FAQ'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='report1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page1', to='story.Story'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='report2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page2', to='story.Story'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='report3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page3', to='story.Story'),
        ),
    ]
