# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_alter_faq_and_coverage_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='faq1',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='faq2',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='faq3',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='report1',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='report2',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='report3',
        ),
    ]
