# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0006_remove_snippets_from_landing_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='about_content',
            field=wagtail.wagtailcore.fields.StreamField([(b'paragraph', wagtail.wagtailcore.blocks.TextBlock())], blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='about_header',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='collaborate_content',
            field=wagtail.wagtailcore.fields.StreamField([(b'paragraph', wagtail.wagtailcore.blocks.TextBlock())], blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='collaborate_header',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
