# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-13 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('landing_page', '0007_add_about_collaborate_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='LandingPage',
        ),
    ]
