# Generated by Django 2.1.3 on 2018-12-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ATTACHMENT_REQUEST', 'ATTACHMENT_REQUEST'), ('ATTACHMENT_AVAILABLE', 'ATTACHMENT_AVAILABLE')], max_length=255)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('from_email', models.EmailField(max_length=255)),
            ],
        ),
    ]
