# Generated by Django 2.1.3 on 2018-12-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
