#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $POSTGRES_APP_USER;
    ALTER USER $POSTGRES_APP_USER WITH ENCRYPTED PASSWORD '$POSTGRES_APP_PASSWORD';
    ALTER USER $POSTGRES_APP_USER WITH SUPERUSER;
    CREATE DATABASE $POSTGRES_APP_DB WITH ENCODING 'UTF8' LC_COLLATE='en-US' LC_CTYPE='en-US' TEMPLATE=template0;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_APP_DB TO $POSTGRES_APP_USER;
    CREATE USER numeracy;
    ALTER USER numeracy WITH ENCRYPTED PASSWORD '$POSTGRES_NUMERACY_PASSWORD';
    CREATE USER notebook;
    ALTER USER notebook WITH ENCRYPTED PASSWORD '$POSTGRES_NOTEBOOK_PASSWORD';
    CREATE USER civis;
    ALTER USER notebook WITH ENCRYPTED PASSWORD '$POSTGRES_CIVIS_PASSWORD';
EOSQL
