---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cpdp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - ${DESKTOP_DOMAIN}
        - ${MOBILE_DOMAIN}
        - ${API_DOMAIN}
      secretName: tls-secret
  rules:
    - host: ${DESKTOP_DOMAIN}
      http:
        paths:
          - path: /admin
            pathType: ImplementationSpecific
            backend:
              service:
                name: gunicorn
                port:
                  number: 80
          - path: /sitemap
            pathType: ImplementationSpecific
            backend:
              service:
                name: gunicorn
                port:
                  number: 80
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: desktop-frontend
                port:
                  number: 80
    - host: ${MOBILE_DOMAIN}
      http:
        paths:
          - path: /admin
            pathType: ImplementationSpecific
            backend:
              service:
                name: gunicorn
                port:
                  number: 80
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: mobile-frontend
                port:
                  number: 80
    - host: ${API_DOMAIN}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: gunicorn
                port:
                  number: 80
