# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 09:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('slug', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descriptor_class', models.CharField(max_length=255)),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
