# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-26 03:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20161025_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
