# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-10 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_faqpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
