# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-01 08:27
from __future__ import unicode_literals

from django.db import migrations

def apply_sample_tags(apps, schema_editor):
    FAQPage = apps.get_model('cms', 'FAQPage')
    faq = FAQPage.objects.first()
    if faq is not None:
        faq.tags = ['Sample']
        faq.save()

    ReportPage = apps.get_model('cms', 'ReportPage')
    report = ReportPage.objects.first()
    if report is not None:
        report.tags = ['Sample']
        report.save()

    Officer = apps.get_model('data', 'Officer')
    officers_named_john = Officer.objects.filter(first_name__contains='John')
    officers_named_john.update(tags=['Officers Named John'])

class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20170301_0223'),
        ('data', '0007_officer_tags'),
    ]

    operations = [
        migrations.RunPython(apply_sample_tags),
    ]
