# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-14 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20170301_0227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQPage',
        ),
    ]
