# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-15 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_delete_faqpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportpage',
            name='officers',
        ),
        migrations.DeleteModel(
            name='ReportPage',
        ),
    ]
