# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_add_full_name_to_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='unit',
        ),
        migrations.AlterField(
            model_name='area',
            name='area_type',
            field=models.CharField(choices=[[b'beat', b'Beat'], [b'neighborhoods', b'Neighborhood'], [b'police-beats', b'Police Beat'], [b'school-grounds', b'School Ground'], [b'wards', b'Ward'], [b'Community', b'Community'], [b'police-districts', b'Police District']], max_length=30),
        ),
    ]
