# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_add_full_name_to_officer'),
        ('data', '0002_alter_choice_fields'),
    ]

    operations = [
    ]
