# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_unit_from_officer'),
        ('data', '0003_merge'),
    ]

    operations = [
    ]
