# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='age_at_march_11_2016',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='full_name',
        ),
        migrations.AddField(
            model_name='officer',
            name='birth_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
