# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-31 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_officer_add_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='rank',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
