# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-10 04:37
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_officer_rank_freeform'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=[], size=None),
        ),
    ]
