# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-14 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_officer_rank_freeform'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeunit',
            name='description',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
