# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-27 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_policeunit_description'),
        ('data', '0007_officer_tags'),
    ]

    operations = [
    ]
