# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-24 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='rank',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
