# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-20 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20170227_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Involvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('involved_type', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('race', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField(null=True)),
                ('allegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Allegation')),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Officer')),
            ],
        ),
    ]
