# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-22 03:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_involvement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[[b'video', b'Video'], [b'audio', b'Audio'], [b'document', b'Document']], db_index=True, max_length=10)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(db_index=True, max_length=255)),
                ('additional_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('tag', models.CharField(max_length=50)),
                ('original_url', models.CharField(db_index=True, max_length=255)),
                ('allegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_files', to='data.Allegation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attachmentfile',
            unique_together=set([('allegation', 'original_url')]),
        ),
    ]
