# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-27 08:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20170321_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), default=[], size=None),
        ),
        migrations.AddField(
            model_name='policeunit',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), default=[], size=None),
        ),
    ]
