# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_area_policeunit_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('incident_start_date', models.DateField(null=True)),
                ('incident_end_date', models.DateField(null=True)),
                ('current_status', models.CharField(max_length=20)),
                ('request_date', models.DateField()),
                ('rank', models.CharField(blank=True, max_length=100)),
                ('last_promotion_date', models.DateField(null=True)),
                ('requester_full_name', models.CharField(max_length=255, null=True)),
                ('ceremony_date', models.DateField(null=True)),
                ('tracking_no', models.BigIntegerField(null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Officer')),
            ],
        ),
    ]
