# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_area_policeunit_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('allegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Allegation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attachmentrequest',
            unique_together=set([('allegation', 'email')]),
        ),
    ]
