# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_award'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigator',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='current_report',
        ),
        migrations.AlterField(
            model_name='investigator',
            name='name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
