# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_0016_investigator_remove_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('race', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('allegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Allegation')),
            ],
        ),
    ]
