# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20171019_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='type',
            new_name='award_type',
        ),
    ]
