# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_rename_field_type_to_award_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='resignation_date',
            field=models.DateField(null=True),
        ),
    ]
