# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_turn_falsy_race_fields_into_unknown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_type',
            field=models.CharField(choices=[[b'beat', b'Beat'], [b'neighborhoods', b'Neighborhood'], [b'police-beats', b'Police Beat'], [b'school-grounds', b'School Ground'], [b'wards', b'Ward'], [b'community', b'Community'], [b'police-districts', b'Police District']], max_length=30),
        ),
    ]
