# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20171219_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigatorAllegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_star', models.CharField(max_length=10, null=True)),
                ('current_rank', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='allegation',
            name='investigator',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='current_rank',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='raw_name',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='unit',
        ),
        migrations.AddField(
            model_name='investigator',
            name='appointed_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='investigator',
            name='first_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investigator',
            name='last_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investigator',
            name='middle_initial',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='investigator',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Officer'),
        ),
        migrations.AddField(
            model_name='investigator',
            name='suffix_name',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='investigatorallegation',
            name='allegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Allegation'),
        ),
        migrations.AddField(
            model_name='investigatorallegation',
            name='current_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.PoliceUnit'),
        ),
        migrations.AddField(
            model_name='investigatorallegation',
            name='investigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Investigator'),
        ),
    ]
