# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_add_investigatorallegation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacePopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='median_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='racepopulation',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Area'),
        ),
    ]
