# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-02 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_add_race_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentfile',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='attachmentfile',
            name='preview_image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
