# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-31 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_add_race_population'),
        ('data', '0027_officer_complaint_percentile'),
    ]

    operations = [
    ]
