# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_merge_20180131_1334'),
        ('data', '0028_add_attachment_meta_info'),
    ]

    operations = [
    ]
