# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_merge_20180207_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='incident_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='incident_start_date',
            new_name='start_date',
        ),
    ]
