# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_rename_award_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policewitness',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='policewitness',
            name='race',
        ),
    ]
