# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_remove_policewitness_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='middle_initial2',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
