# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_officer_middle_initial2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_grade', models.CharField(max_length=16)),
                ('rank', models.CharField(max_length=64, null=True)),
                ('salary', models.PositiveIntegerField()),
                ('employee_status', models.CharField(max_length=32)),
                ('org_hire_date', models.DateField(null=True)),
                ('spp_date', models.DateField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('age_at_hire', models.PositiveSmallIntegerField(null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Officer')),
            ],
        ),
    ]
