# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-04 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='alderman',
            field=models.CharField(blank=True, help_text=b'Alderman of Ward', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='commander',
            field=models.CharField(blank=True, help_text=b'Police District Commander', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='description',
            field=models.CharField(blank=True, help_text=b'Another name for area', max_length=255, null=True),
        ),
    ]
