# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-18 03:28
from __future__ import unicode_literals
from contextlib import contextmanager
from csv import DictReader
import os
from tempfile import NamedTemporaryFile

from django.conf import settings
from django.db import migrations

from azure.storage.blob import BlockBlobService


@contextmanager
def csv_from_azure(filename):
    block_blob_service = BlockBlobService(
        account_name=settings.DATA_PIPELINE_STORAGE_ACCOUNT_NAME,
        account_key=settings.DATA_PIPELINE_STORAGE_ACCOUNT_KEY
    )
    tmp_file = NamedTemporaryFile(suffix='.csv', delete=False)
    block_blob_service.get_blob_to_path('csv', filename, tmp_file.name)
    csvfile = open(tmp_file.name)
    reader = DictReader(csvfile)
    yield reader
    csvfile.close()
    os.remove(tmp_file.name)


def import_award_data(apps, schema_editor):
    with csv_from_azure('20180518_award.csv') as reader:
        pks = []

        Award = apps.get_model('data', 'Award')
        blank_or_null = {
            field.name: None if field.null else ''
            for field in Award._meta.get_fields()
        }
        for row in reader:
            for key, val in row.iteritems():
                if val == '':
                    row[key] = blank_or_null[key]
            pks.append(int(row['pk']))
            award, created = Award.objects.update_or_create(
                id=int(row['pk']),
                defaults={
                    'officer_id': row['officer_id'],
                    'award_type': row['award_type'],
                    'start_date': row['start_date'],
                    'end_date': row['end_date'],
                    'current_status': row['current_status'],
                    'request_date': row['request_date'],
                    'rank': row['rank'],
                    'last_promotion_date': row['last_promotion_date'],
                    'requester_full_name': row['requester_full_name'],
                    'ceremony_date': row['ceremony_date'],
                    'tracking_no': row['tracking_no']
                }
            )

    Award.objects.exclude(pk__in=pks).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_import_new_officers_data'),
    ]

    operations = [
        migrations.RunPython(
                import_award_data,
                reverse_code=migrations.RunPython.noop,
                elidable=True),
    ]
