# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_import_officerbadgenumber_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allegation',
            name='add1',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='allegation',
            name='location',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
