# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_allegation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allegation',
            name='add1',
            field=models.CharField(blank=True, default='', max_length=16),
            preserve_default=False,
        ),
    ]
