# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 09:42
from __future__ import unicode_literals

from django.db import migrations


def alter_data(apps, schema_editor):
    Allegation = apps.get_model('data', 'Allegation')
    Area = apps.get_model('data', 'Area')
    LineArea = apps.get_model('data', 'LineArea')

    for allegation in Allegation.objects.all():
        if allegation.point is None:
            allegation.areas.set([])
            allegation.line_areas.set([])
        else:
            allegation.areas.set(Area.objects.filter(polygon__covers=allegation.point))
            allegation.line_areas.set(LineArea.objects.filter(geom__covers=allegation.point))


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_import_allegation_data'),
    ]

    operations = [
        migrations.RunPython(
            alter_data,
            reverse_code=migrations.RunPython.noop,
            elidable=True),
    ]
