# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 08:43
from __future__ import unicode_literals

import data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_officerallegation_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigator',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='investigator',
            name='race',
            field=models.CharField(default=b'Unknown', max_length=50, validators=[data.validators.validate_race]),
        ),
        migrations.AddField(
            model_name='investigatorallegation',
            name='investigator_type',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
