# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_import_investigatorallegation_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainant',
            name='birth_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='birth_year',
            field=models.IntegerField(null=True),
        ),
    ]
