# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-05 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0056_import_officerallegation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='allegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victims', to='data.Allegation'),
        ),
    ]
