# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-06 02:44
from __future__ import unicode_literals
from datetime import datetime

from django.db import migrations

import pytz


def remove_data(apps, schema_editor):
    Allegation = apps.get_model('data', 'Allegation')
    Allegation.objects.filter(incident_date__lt=datetime(1988, 1, 1, tzinfo=pytz.utc)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0056_import_officerallegation_data'),
    ]

    operations = [
        migrations.RunPython(
                remove_data,
                reverse_code=migrations.RunPython.noop,
                elidable=True),
    ]
