# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-22 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_remove-pre-1988-data'),
    ]

    operations = [
        migrations.AddField(
            model_name='allegation',
            name='old_complaint_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
