# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-18 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_victim_allegation_related_name'),
        ('data', '0057_remove-pre-1988-data'),
    ]

    operations = [
    ]
