# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-22 01:39
from __future__ import unicode_literals
import re

from django.db import migrations
from django.contrib.gis.geos import Point

from data.migration_utils import csv_from_azure


def import_data(apps, schema_editor):
    Allegation = apps.get_model('data', 'Allegation')

    with csv_from_azure('20180622_old_complaint_geocoded.csv') as reader:
        prog = re.compile(r'(\d+)\*\*')
        for row in reader:
            try:
                allegation = Allegation.objects.get(crid=row['cr_id'])
            except Allegation.DoesNotExist:
                continue
            latlng = row['latlng'].split(' ')
            allegation.point = Point(float(latlng[1]), float(latlng[0]))
            allegation.old_complaint_address = prog.sub(r'\1XX', row['full_address'])
            allegation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_allegation_old_complaint_address'),
    ]

    operations = [
        migrations.RunPython(
                import_data,
                reverse_code=migrations.RunPython.noop,
                elidable=True),
    ]
