# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0059_import_old_complaint_address_latlng'),
        ('data', '0058_merge_20180617_2214'),
    ]

    operations = [
    ]
