# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 08:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models

from data.migration_utils import csv_from_azure


def import_data(apps, schema_editor):
    OfficerAllegation = apps.get_model('data', 'OfficerAllegation')
    blank_or_null = {
        '%s_id' % field.name if field.is_relation else field.name: None if field.null else ''
        for field in OfficerAllegation._meta.get_fields()
    }
    boolean_fields = [
        field.name for field in OfficerAllegation._meta.get_fields()
        if type(field) in [models.fields.BooleanField, models.fields.NullBooleanField]
    ]
    boolean_map = {
        'False': False,
        'True': True
    }

    with csv_from_azure('20180711_officerallegation_before_1988.csv') as reader:
        for row in reader:
            for key, val in row.items():
                if val == '':
                    row[key] = blank_or_null[key]
                elif key in boolean_fields:
                    row[key] = boolean_map[val]
            pk = int(row.pop('pk'))
            obj, created = OfficerAllegation.objects.update_or_create(
                id=pk,
                defaults=row
            )


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0061_import_allegation_before_1988'),
    ]

    operations = [
        migrations.RunPython(
                import_data,
                reverse_code=migrations.RunPython.noop,
                elidable=True),
    ]
