# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-23 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0065_racepopulation_shorten_race_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='civilian_allegation_percentile',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='honorable_mention_percentile',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='internal_allegation_percentile',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='trr_percentile',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='complaint_percentile',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
    ]
