# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0066_add_officer_percentile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='allegation_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='sustained_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
