# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-07 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0066_add_officer_percentile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
