# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-21 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0069_add_officer_and_allegation_cached_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentfile',
            name='external_id',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
