# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0081_add_allegation_cached_data_and_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerYearlyPercentile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('percentile_trr', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('percentile_allegation', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('percentile_allegation_civilian', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('percentile_allegation_internal', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='allegation',
            name='coaccused_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='allegation',
            name='police_witnesses',
            field=models.ManyToManyField(through='data.PoliceWitness', to='data.Officer'),
        ),
        migrations.AddField(
            model_name='officer',
            name='civilian_compliment_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='current_badge',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='current_salary',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='discipline_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='honorable_mention_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='last_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.PoliceUnit'),
        ),
        migrations.AddField(
            model_name='officer',
            name='major_award_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='trr_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='unsustained_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddIndex(
            model_name='officerbadgenumber',
            index=models.Index(fields=[b'current'], name='data_office_current_f8bc5a_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=[b'year'], name='data_salary_year_51b276_idx'),
        ),
        migrations.AddIndex(
            model_name='officerallegation',
            index=models.Index(fields=[b'start_date'], name='data_office_start_d_8e9651_idx'),
        ),
        migrations.AddIndex(
            model_name='officerhistory',
            index=models.Index(fields=[b'end_date'], name='data_office_end_dat_a1e9be_idx'),
        ),
        migrations.AddIndex(
            model_name='officerhistory',
            index=models.Index(fields=[b'effective_date'], name='data_office_effecti_f0cc97_idx'),
        ),
        migrations.AddField(
            model_name='officeryearlypercentile',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Officer'),
        ),
        migrations.AddIndex(
            model_name='officeryearlypercentile',
            index=models.Index(fields=[b'year'], name='data_office_year_c8b488_idx'),
        ),
    ]
