# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-02 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0082_add_officer_and_allegation_cached_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='rank_changed',
            field=models.BooleanField(default=False),
        ),
    ]
