# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-01 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0083_salary_rank_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentrequest',
            name='added_to_foia_airtable',
            field=models.BooleanField(default=False),
        ),
    ]
