# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 06:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0084_attachmentrequest_added_to_foia_airtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentfile',
            name='additional_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
