# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-26 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0084_attachmentrequest_added_to_foia_airtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='has_unique_name',
            field=models.BooleanField(default=False),
        ),
    ]
