# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 04:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0085_set_attachmentfile_additional_info_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='allegation',
            name='subjects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None),
        ),
    ]
