# Generated by Django 2.1.3 on 2018-11-23 08:18

import data.validators
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0086_rename_officer_rank_po_and_det'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allegation',
            name='beat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beats', to='data.Area'),
        ),
        migrations.AlterField(
            model_name='allegation',
            name='most_common_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.AllegationCategory'),
        ),
        migrations.AlterField(
            model_name='allegationcategory',
            name='citizen_dept',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('dept', 'Dept'), ('?', 'Unknown')], default='citizen', max_length=50),
        ),
        migrations.AlterField(
            model_name='area',
            name='alderman',
            field=models.CharField(help_text='Alderman of Ward', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_type',
            field=models.CharField(choices=[['beat', 'Beat'], ['neighborhoods', 'Neighborhood'], ['police-beats', 'Police Beat'], ['school-grounds', 'School Ground'], ['wards', 'Ward'], ['community', 'Community'], ['police-districts', 'Police District']], max_length=30),
        ),
        migrations.AlterField(
            model_name='area',
            name='commander',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Officer'),
        ),
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.CharField(blank=True, help_text='Another name for area', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='police_hq',
            field=models.ForeignKey(help_text='This beat contains police-district HQ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Area'),
        ),
        migrations.AlterField(
            model_name='area',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='attachmentfile',
            name='file_type',
            field=models.CharField(choices=[['video', 'Video'], ['audio', 'Audio'], ['document', 'Document']], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='complainant',
            name='race',
            field=models.CharField(default='Unknown', max_length=50, validators=[data.validators.validate_race]),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Officer'),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='race',
            field=models.CharField(default='Unknown', max_length=50, validators=[data.validators.validate_race]),
        ),
        migrations.AlterField(
            model_name='investigatorallegation',
            name='current_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.PoliceUnit'),
        ),
        migrations.AlterField(
            model_name='involvement',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Officer'),
        ),
        migrations.AlterField(
            model_name='involvement',
            name='race',
            field=models.CharField(default='Unknown', max_length=50, validators=[data.validators.validate_race]),
        ),
        migrations.AlterField(
            model_name='linearea',
            name='linearea_type',
            field=models.CharField(choices=[['passageway', 'Passageway']], max_length=30),
        ),
        migrations.AlterField(
            model_name='officer',
            name='active',
            field=models.CharField(choices=[['Yes', 'Active'], ['No', 'Inactive'], ['Unknown', 'Unknown']], default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='officer',
            name='last_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.PoliceUnit'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='race',
            field=models.CharField(default='Unknown', max_length=50, validators=[data.validators.validate_race]),
        ),
        migrations.AlterField(
            model_name='officer',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='officerallegation',
            name='allegation_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.AllegationCategory'),
        ),
        migrations.AlterField(
            model_name='officerallegation',
            name='final_finding',
            field=models.CharField(blank=True, choices=[['UN', 'Unfounded'], ['EX', 'Exonerated'], ['NS', 'Not Sustained'], ['SU', 'Sustained'], ['NC', 'No Cooperation'], ['NA', 'No Affidavit'], ['DS', 'Discharged'], ['ZZ', 'Unknown']], max_length=2),
        ),
        migrations.AlterField(
            model_name='officerallegation',
            name='recc_finding',
            field=models.CharField(blank=True, choices=[['UN', 'Unfounded'], ['EX', 'Exonerated'], ['NS', 'Not Sustained'], ['SU', 'Sustained'], ['NC', 'No Cooperation'], ['NA', 'No Affidavit'], ['DS', 'Discharged'], ['ZZ', 'Unknown']], max_length=2),
        ),
        migrations.AlterField(
            model_name='policeunit',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='victim',
            name='race',
            field=models.CharField(default='Unknown', max_length=50, validators=[data.validators.validate_race]),
        ),
    ]
