# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 03:21
from __future__ import unicode_literals

from django.db import migrations
from django.db.models.expressions import F

from data.constants import AttachmentSourceType


def set_source_type(apps, schema_editor):
    AttachmentFile = apps.get_model('data', 'AttachmentFile')
    AttachmentFile.objects.filter(url__icontains='documentcloud').update(source_type=AttachmentSourceType.DOCUMENTCLOUD)
    AttachmentFile.objects.filter(url__icontains='chicagocopa').update(source_type=AttachmentSourceType.COPA)
    AttachmentFile.objects.exclude(
        source_type=AttachmentSourceType.DOCUMENTCLOUD
    ).update(external_id=F('original_url'))


def remove_chicagocopa_external_id(apps, schema_editor):
    AttachmentFile = apps.get_model('data', 'AttachmentFile')
    AttachmentFile.objects.exclude(
        source_type=AttachmentSourceType.DOCUMENTCLOUD
    ).update(external_id='')


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0087_attachmentfile_add_source_type_alter_external_id'),
    ]

    operations = [
        migrations.RunPython(
            set_source_type,
            reverse_code=remove_chicagocopa_external_id,
            elidable=True),
    ]
