# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0088_attachmentfile_correct_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentfile',
            name='external_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='attachmentfile',
            unique_together=set([('allegation', 'external_id', 'source_type')]),
        ),
    ]
