# Generated by Django 2.1.3 on 2018-11-30 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0087_add_on_delete_to_several_models'),
        ('data', '0089_attachmentfile_change_unique_together'),
    ]

    operations = [
    ]
