# Generated by Django 2.1.3 on 2018-12-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0091_correct_allegations_subjects_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentrequest',
            name='added_to_foia_airtable',
        ),
        migrations.AddField(
            model_name='attachmentrequest',
            name='airtable_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
