# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 03:21
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F

from data.models import AttachmentFile
from data.constants import AttachmentSourceType


def extract_external_id_from_url(apps, schema_editor):
    non_documentcloud_files = AttachmentFile.objects.exclude(source_type=AttachmentSourceType.DOCUMENTCLOUD)
    for file in non_documentcloud_files:
        url = file.original_url
        file.external_id = url[url.rindex('/') + 1:] if '/' in url else url

    AttachmentFile.objects.bulk_update(non_documentcloud_files, update_fields=['external_id'], batch_size=1000)


def use_url_for_external_id(apps, schema_editor):
    AttachmentFile.objects.exclude(
        source_type=AttachmentSourceType.DOCUMENTCLOUD
    ).update(external_id=F('original_url'))


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0091_correct_allegations_subjects_default'),
    ]

    operations = [
        migrations.RunPython(
            extract_external_id_from_url,
            reverse_code=use_url_for_external_id,
            elidable=True),
    ]
