# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 03:21
from __future__ import unicode_literals

from tqdm import tqdm

from django.db import migrations
from django.db.models import F


def extract_external_id_from_url(apps, schema_editor):
    AttachmentFile = apps.get_model('data', 'AttachmentFile')
    non_documentcloud_files = AttachmentFile.objects.exclude(source_type='DOCUMENTCLOUD')
    for file in tqdm(non_documentcloud_files, desc='Get external_id from original_url '):
        url = file.original_url
        file.external_id = url[url.rindex('/') + 1:] if '/' in url else url
        file.save()


def use_url_for_external_id(apps, schema_editor):
    AttachmentFile = apps.get_model('data', 'AttachmentFile')
    AttachmentFile.objects.exclude(source_type='DOCUMENTCLOUD').update(external_id=F('original_url'))


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0093_attachment_request_add_airtable_record_id'),
    ]

    operations = [
        migrations.RunPython(
            extract_external_id_from_url,
            reverse_code=use_url_for_external_id,
            elidable=True),
    ]
