# Generated by Django 2.1.3 on 2018-12-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0093_attachment_request_add_airtable_record_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachmentfile',
            old_name='created_at',
            new_name='external_created_at',
        ),
        migrations.RenameField(
            model_name='attachmentfile',
            old_name='last_updated',
            new_name='external_last_updated',
        ),
    ]
