# Generated by Django 2.1.3 on 2018-12-26 09:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0093_attachment_request_add_airtable_record_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='attachmentrequest',
            managers=[
                ('bulk_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
