# Generated by Django 2.1.3 on 2018-12-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0094_change_attachmentfile_external_columns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachmentrequest',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
