# Generated by Django 2.1.3 on 2018-12-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0095_attachmentfile_copa_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentrequest',
            name='noti_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
