# Generated by Django 2.1.3 on 2019-01-02 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0096_add_created_at_and_updated_at_columns'),
        ('data', '0095_attachmenrequest_bulk_objects_manager'),
    ]

    operations = [
    ]
