# Generated by Django 2.1.3 on 2018-12-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0097_merge_20190101_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentfile',
            name='text_content',
            field=models.TextField(blank=True),
        ),
    ]
