# Generated by Django 2.1.3 on 2019-01-08 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0100_populate_new_allegation_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allegation',
            name='police_witnesses',
        ),
        migrations.RemoveField(
            model_name='complainant',
            name='allegation_old_fk',
        ),
        migrations.RemoveField(
            model_name='investigatorallegation',
            name='allegation_old_fk',
        ),
        migrations.RemoveField(
            model_name='involvement',
            name='allegation_old_fk',
        ),
        migrations.RemoveField(
            model_name='officerallegation',
            name='allegation_old_fk',
        ),
        migrations.RemoveField(
            model_name='policewitness',
            name='allegation_old_fk',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='allegation_old_fk',
        ),
    ]
