# Generated by Django 2.1.3 on 2019-01-08 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0101_remove_allegation_old_fk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attachmentfile',
            unique_together={('allegation', 'external_id', 'source_type')},
        ),
        migrations.AlterUniqueTogether(
            name='attachmentrequest',
            unique_together={('allegation', 'email')},
        ),
    ]
