# Generated by Django 2.1.3 on 2019-01-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0103_remove_attachment_allegation_old_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allegation',
            name='id',
        ),
        migrations.AlterField(
            model_name='allegation',
            name='crid',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
