# Generated by Django 2.1.3 on 2019-01-08 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0104_make_crid_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentfile',
            name='allegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_files', to='data.Allegation'),
        ),
        migrations.AlterField(
            model_name='attachmentrequest',
            name='allegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Allegation'),
        ),
        migrations.AlterField(
            model_name='complainant',
            name='allegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Allegation'),
        ),
        migrations.AlterField(
            model_name='investigatorallegation',
            name='allegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Allegation'),
        ),
        migrations.AlterField(
            model_name='involvement',
            name='allegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Allegation'),
        ),
        migrations.AlterField(
            model_name='officerallegation',
            name='allegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Allegation'),
        ),
        migrations.AlterField(
            model_name='policewitness',
            name='allegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Allegation'),
        ),
        migrations.AlterField(
            model_name='victim',
            name='allegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victims', to='data.Allegation'),
        ),
    ]
