# Generated by Django 2.1.3 on 2019-01-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0105_change_allegation_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='allegation',
            name='police_witnesses',
            field=models.ManyToManyField(through='data.PoliceWitness', to='data.Officer'),
        ),
    ]
