# Generated by Django 2.1.3 on 2019-01-08 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0106_add_field_police_witnesses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allegation',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='allegation',
            name='line_areas',
        ),
    ]
