# Generated by Django 2.1.3 on 2019-01-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0107_remove_area_line_area_from_allegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='allegation',
            name='areas',
            field=models.ManyToManyField(to='data.Area'),
        ),
        migrations.AddField(
            model_name='allegation',
            name='line_areas',
            field=models.ManyToManyField(to='data.LineArea'),
        ),
    ]
