# Generated by Django 2.1.3 on 2019-01-08 03:54

from django.db import migrations
from django.contrib.gis.measure import D

from tqdm import tqdm


def populate_areas_lineareas(apps, schema_editor):
    Allegation = apps.get_model('data', 'Allegation')
    Area = apps.get_model('data', 'Area')
    LineArea = apps.get_model('data', 'LineArea')
    distance = D(m=10)

    for allegation in tqdm(
        Allegation.objects.all(),
        desc='Updating areas and line_areas'
    ):
        if allegation.point is None:
            allegation.areas.set([])
            allegation.line_areas.set([])
        else:
            allegation.areas.set(Area.objects.filter(polygon__covers=allegation.point))
            allegation.line_areas.set(LineArea.objects.filter(geom__distance_lte=(allegation.point, distance)))


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0108_add_area_line_area_to_allegation'),
    ]

    operations = [
        migrations.RunPython(
                populate_areas_lineareas,
                reverse_code=migrations.RunPython.noop,
                elidable=True),
    ]
