# Generated by Django 2.1.3 on 2019-01-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0099_attachmentrequest_noti_email_sent'),
        ('data', '0109_populate_areas_lineareas'),
    ]

    operations = [
    ]
