# Generated by Django 2.1.3 on 2019-02-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0110_merge_20190108_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentfile',
            name='downloads_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attachmentfile',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
