# Generated by Django 2.1.3 on 2019-02-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0111_add_views_count_and_downloads_count_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentfile',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
