# Generated by Django 2.1.3 on 2019-02-25 03:08

from django.db import migrations, models
from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0112_attachmentfile_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentfile',
            name='notifications_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attachmentfile',
            name='pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attachmentfile',
            name='manually_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachmentfile',
            name='last_updated_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
