# Generated by Django 2.1.3 on 2019-02-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0113_attachmentfile_add_pages_count_and_notifications_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentfile',
            name='pages',
            field=models.IntegerField(default=0),
        ),
    ]
