# Generated by Django 2.1.3 on 2019-02-22 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0114_attachmentfile_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentfile',
            name='pages_count',
        ),
    ]
