# Generated by Django 2.1.3 on 2019-02-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0114_populate_attachmentfile_notifications_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentfile',
            name='manually_updated',
            field=models.BooleanField(default=False),
        ),
    ]
