# Generated by Django 2.1.3 on 2019-03-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0115_populate_attachmentfile_notifications_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentfile',
            name='pending_documentcloud_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attachmentfile',
            name='upload_fail_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
