# Generated by Django 2.1.3 on 2019-02-22 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0115_remove_attachmentfile_pages_count'),
    ]

    def populate_notifications_count(apps, schema_editor):
        AttachmentFile = apps.get_model('data', 'AttachmentFile')
        AttachmentRequest = apps.get_model('data', 'AttachmentRequest')

        for attachment in AttachmentFile.objects.filter(file_type='document'):
            attachment.notifications_count = AttachmentRequest.bulk_objects.filter(
                noti_email_sent=True, allegation_id=attachment.allegation_id
            ).count()
            attachment.save()

    operations = [
        migrations.RunPython(
            populate_notifications_count,
            reverse_code=migrations.RunPython.noop,
            elidable=True),
    ]
