# Generated by Django 2.1.11 on 2019-08-08 05:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0116_attachmentfile_add_documentcloud_information_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentfile',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), default=list, size=None),
        ),
    ]
