# Generated by Django 2.1.11 on 2019-11-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0117_attachmentfile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentfile',
            name='reprocess_text_count',
            field=models.IntegerField(default=0),
        ),
    ]
