# Generated by Django 2.1.11 on 2019-12-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0118_attachmentfile_reprocess_text_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='allegation',
            name='is_extracted_summary',
            field=models.BooleanField(default=False),
        ),
    ]
