# Generated by Django 2.2.9 on 2020-02-12 08:53

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0119_add_is_extracted_summary_field_to_allegation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='attachmentfile',
            name='tags',
        ),
        migrations.AddField(
            model_name='attachmentfile',
            name='tags',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='data.Tag'),
        ),
    ]
