# Generated by Django 2.2.10 on 2020-05-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0121_allow_tags_to_be_blanked'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentfile',
            name='is_external_ocr',
            field=models.BooleanField(default=False),
        ),
    ]
