# Generated by Django 2.2.10 on 2020-06-18 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('data', '0123_migrate_from_allegation_to_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attachmentfile',
            unique_together={('owner_id', 'owner_type', 'external_id', 'source_type')},
        ),
        migrations.RemoveField(
            model_name='attachmentfile',
            name='allegation',
        ),
    ]
