# Generated by Django 2.2.10 on 2020-05-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0123_attachmentocr'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentNarrative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_num', models.IntegerField()),
                ('section_name', models.CharField(max_length=255)),
                ('column_name', models.CharField(max_length=255)),
                ('text_content', models.TextField(blank=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_narratives', to='data.AttachmentFile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
