# Generated by Django 2.2.10 on 2020-07-31 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('data', '0126_migrate_from_allegation_to_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentfile',
            name='allegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Allegation'),
        ),
        migrations.AlterUniqueTogether(
            name='attachmentfile',
            unique_together={('owner_id', 'owner_type', 'external_id', 'source_type')},
        ),
    ]
