# Generated by Django 2.2.10 on 2020-07-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0127_model_attachmentfile_allow_null_allegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='allegations',
            field=models.ManyToManyField(through='data.OfficerAllegation', to='data.Allegation'),
        ),
    ]
