# Generated by Django 2.2.10 on 2020-09-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0128_officer_allegations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allegationcategory',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
