# Generated by Django 2.2.10 on 2024-05-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0129_add_db_index_to_allegation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentfile',
            name='allegation',
        ),
        migrations.AlterField(
            model_name='officerallegation',
            name='final_finding',
            field=models.CharField(blank=True, choices=[['UN', 'Unfounded'], ['EX', 'Exonerated'], ['NS', 'Not Sustained'], ['SU', 'Sustained'], ['NC', 'No Cooperation'], ['NA', 'No Affidavit'], ['DS', 'Discharged'], ['ZZ', 'Unknown']], max_length=3),
        ),
        migrations.AlterField(
            model_name='officerallegation',
            name='recc_finding',
            field=models.CharField(blank=True, choices=[['UN', 'Unfounded'], ['EX', 'Exonerated'], ['NS', 'Not Sustained'], ['SU', 'Sustained'], ['NC', 'No Cooperation'], ['NA', 'No Affidavit'], ['DS', 'Discharged'], ['ZZ', 'Unknown']], max_length=3),
        ),
    ]
