# Generated by Django 2.2.10 on 2024-07-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0132_auto_20240609_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerallegation',
            name='final_outcome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
