# Generated by Django 2.2.10 on 2024-07-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0133_auto_20240716_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerallegation',
            name='recc_outcome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
