# Generated by Django 2.2.10 on 2024-08-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0134_auto_20240716_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigatorallegation',
            name='investigating_agency',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
