# Generated by Django 2.2.10 on 2024-08-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0135_add_investigating_agency_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerallegation',
            name='final_finding',
            field=models.CharField(blank=True, choices=[['UN', 'Unfounded'], ['EX', 'Exonerated'], ['AC', 'Administratively Closed'], ['NS', 'Not Sustained'], ['SU', 'Sustained'], ['NC', 'No Cooperation'], ['NA', 'No Affidavit'], ['DS', 'Discharged'], ['ZZ', 'Unknown']], max_length=3),
        ),
        migrations.AlterField(
            model_name='officerallegation',
            name='recc_finding',
            field=models.CharField(blank=True, choices=[['UN', 'Unfounded'], ['EX', 'Exonerated'], ['AC', 'Administratively Closed'], ['NS', 'Not Sustained'], ['SU', 'Sustained'], ['NC', 'No Cooperation'], ['NA', 'No Affidavit'], ['DS', 'Discharged'], ['ZZ', 'Unknown']], max_length=30),
        )
    ]
