# Generated by Django 2.2.10 on 2026-03-07 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0136_add_allegation_category_and_drop_not_null_constraint_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officerallegation',
            name='final_finding',
        ),
        migrations.RemoveField(
            model_name='officerallegation',
            name='recc_finding',
        ),
        migrations.CreateModel(
            name='OfficerAllegationFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recc_finding', models.CharField(blank=True, choices=[['UN', 'Unfounded'], ['EX', 'Exonerated'], ['AC', 'Administratively Closed'], ['NS', 'Not Sustained'], ['SU', 'Sustained'], ['NC', 'No Cooperation'], ['NA', 'No Affidavit'], ['DS', 'Discharged'], ['ZZ', 'Unknown']], max_length=30)),
                ('final_finding', models.CharField(blank=True, choices=[['UN', 'Unfounded'], ['EX', 'Exonerated'], ['AC', 'Administratively Closed'], ['NS', 'Not Sustained'], ['SU', 'Sustained'], ['NC', 'No Cooperation'], ['NA', 'No Affidavit'], ['DS', 'Discharged'], ['ZZ', 'Unknown']], max_length=3)),
                ('final_outcome_class', models.CharField(blank=True, max_length=20)),
                ('allegation_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.AllegationCategory')),
                ('officer_allegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='data.OfficerAllegation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
