# Generated by Django 2.2.10 on 2026-03-07 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0137_add_officer_allegation_finding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officerallegation',
            name='allegation_category',
        ),
        migrations.AlterField(
            model_name='officerallegationfinding',
            name='officer_allegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.OfficerAllegation'),
        ),
    ]
