# Generated by Django 2.2.10 on 2026-09-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0138_remove_category_from_officer_allegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='allegationcategory',
            name='ranking',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
