# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 03:41
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTermCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('order_number', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='SearchTermItem',
            fields=[
                ('slug', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('call_to_action_type', models.CharField(choices=[(b'view_all', b'View All'), (b'plain_text', b'Plain text'), (b'link', b'Link')], default=b'plain_text', max_length=20)),
                ('link', models.URLField(null=True)),
                ('order_number', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('category', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_terms.SearchTermCategory')),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
    ]
