# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchtermcategory',
            options={'ordering': ['order_number'], 'verbose_name_plural': 'Search term categories'},
        ),
        migrations.AlterField(
            model_name='searchtermitem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
