# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-31 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_terms', '0003_alter_nullable_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtermcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchtermitem',
            name='call_to_action_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
