# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-03 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('search_terms', '0004_add_search_term_category_and_search_term_item_call_to_action_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtermitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
