# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-03 04:11
from __future__ import unicode_literals

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    search_term_item_model = apps.get_model('search_terms', 'searchtermitem')
    for row in search_term_item_model.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('search_terms', '0005_searchtermitem_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
