# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-03 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('search_terms', '0006_populate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtermitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
