# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-03 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('search_terms', '0007_alter_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtermitem',
            name='slug',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='searchtermitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
