# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-04 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_terms', '0008_change_primary_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtermitem',
            name='slug',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
