# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-04 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_terms', '0009_make_slug_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtermitem',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
