# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-04 09:21
from __future__ import unicode_literals

import re

from django.db import migrations


def drop_scheme_and_host(apps, schema_editor):
    search_term_item_model = apps.get_model('search_terms', 'searchtermitem')
    for row in search_term_item_model.objects.all():
        if not row.link:
            continue
        row.link = re.sub(r'https?://beta.cpdb.co(/url-mediator/session-builder\?.+)', r'\1', row.link)
        row.save(update_fields=['link'])


class Migration(migrations.Migration):

    dependencies = [
        ('search_terms', '0010_change_link_to_char'),
    ]

    operations = [
        migrations.RunPython(drop_scheme_and_host, reverse_code=migrations.RunPython.noop),
    ]
