# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0013_area_policeunit_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.Officer')),
            ],
        ),
    ]
