# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_grid', '0002_activitycard_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycard',
            name='last_activity',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activitycard',
            name='officer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_card', to='data.Officer'),
        ),
    ]
