# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-12 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_area_police_hq'),
        ('activity_grid', '0003_auto_20170920_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPairCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('important', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(null=True)),
                ('officer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_card1', to='data.Officer')),
                ('officer2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_card2', to='data.Officer')),
            ],
        ),
    ]
