# Generated by Django 2.1.3 on 2019-02-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_grid', '0006_add_created_at_and_updated_at_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypaircard',
            name='coaccusal_count',
            field=models.IntegerField(default=0),
        ),
    ]
