class AutoCompleteType:
    OFFICER_NAME = 'OFFICER_NAME'
    OFFICER_BADGE = 'OFFICER_BADGE'
    OFFICER_UNIT = 'OFFICER_UNIT'
    AREA_NAME = 'AREA_NAME'
    ALLEGATION_CRID = 'ALLEGATION_CRID'
    ALLEGATION_SUMMARY = 'ALLEGATION_SUMMARY'
    ALLEGATION_CITY = 'ALLEGATION_CITY'
    ALLEGATION_ZIP_CODE = 'ALLEGATION_ZIP_CODE'
