# Generated by Django 2.1.3 on 2019-03-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0115_populate_attachmentfile_notifications_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Untitled Pinboard', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('allegations', models.ManyToManyField(to='data.Allegation')),
                ('officers', models.ManyToManyField(to='data.Officer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
