# Generated by Django 2.1.3 on 2019-04-01 07:47

from django.db import migrations, models
import pinboard.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0115_populate_attachmentfile_notifications_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', pinboard.fields.HexField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('allegations', models.ManyToManyField(to='data.Allegation')),
                ('officers', models.ManyToManyField(to='data.Officer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
