# Generated by Django 2.1.3 on 2019-04-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trr', '0017_add_created_at_and_updated_at_columns'),
        ('pinboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinboard',
            name='trrs',
            field=models.ManyToManyField(to='trr.TRR'),
        ),
    ]
