# Generated by Django 2.1.3 on 2019-04-25 08:48

from django.db import migrations


def create_example_pinboard(apps, schema_editor):
    Pinboard = apps.get_model('pinboard', 'Pinboard')

    skullcap_pinboard, _ = Pinboard.objects.get_or_create(id='22e66085')
    skullcap_pinboard.title = 'Skullcap Crew'
    skullcap_pinboard.description = ''
    skullcap_pinboard.save()
    skullcap_pinboard.officers.set([25503, 25962, 32384, 25732, 27439])

    watts_pinboard, _ = Pinboard.objects.get_or_create(id='b20c2c36')
    watts_pinboard.title = 'Watts Crew'
    watts_pinboard.description = ''
    watts_pinboard.save()
    watts_pinboard.officers.set([
        30215, 19331, 2334, 13777, 20481, 10330, 16181, 15883, 31456,
        23933, 27871, 7771, 3584, 24403, 3564, 26902, 27101
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('pinboard', '0003_pinboard_sorted_many_to_many_fields'),
    ]

    operations = [
        migrations.RunPython(
            create_example_pinboard,
            reverse_code=migrations.RunPython.noop,
            elidable=True
        ),
    ]
