# Generated by Django 2.1.11 on 2019-11-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinboard', '0006_add_example_pinboard_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinboard',
            name='source_pinboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pinboard.Pinboard'),
        ),
    ]
