# Generated by Django 2.1.11 on 2019-11-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0117_attachmentfile_tags'),
        ('pinboard', '0007_add_source_pinboard_to_pinboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyAllegation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('data.allegation',),
        ),
    ]
