# Generated by Django 2.1.11 on 2019-11-21 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinboard', '0008_proxyallegation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinboard',
            name='source_pinboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_pinboards', to='pinboard.Pinboard'),
        ),
    ]
