# Generated by Django 2.2.10 on 2020-06-09 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pinboard', '0009_pinboard_source_pinboard_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinboard',
            name='last_viewed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
