# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trr',
            name='subject_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
