# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_salary'),
        ('trr', '0002_alter_trr_subject_id_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(choices=[(b'Member Action', b'Member Action'), (b'Subject Action', b'Subject Action')], max_length=16, null=True)),
                ('resistance_type', models.CharField(choices=[(b'Active Resister', b'Active Resister'), (b'Passive Resister', b'Passive Resister'), (b'Assailant Battery', b'Assailant Battery'), (b'Assailant Assault/Battery', b'Assailant Assault/Battery'), (b'Assailant Assault', b'Assailant Assault'), (b'Assailant Deadly Force', b'Assailant Deadly Force')], max_length=32, null=True)),
                ('action', models.CharField(max_length=64, null=True)),
                ('other_description', models.CharField(max_length=64, null=True)),
                ('member_action', models.CharField(max_length=64, null=True)),
                ('force_type', models.CharField(max_length=64, null=True)),
                ('action_sub_category', models.SmallIntegerField(null=True)),
                ('action_category', models.SmallIntegerField(null=True)),
                ('resistance_level', models.CharField(choices=[(b'Active', b'Active'), (b'Passive', b'Passive'), (b'Assault/Battery', b'Assault/Battery'), (b'Deadly Force', b'Deadly Force')], max_length=16, null=True)),
                ('trr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trr.TRR')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField(null=True)),
                ('statute', models.CharField(max_length=64, null=True)),
                ('description', models.CharField(max_length=64, null=True)),
                ('subject_no', models.PositiveIntegerField(null=True)),
                ('trr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trr.TRR')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_type', models.CharField(max_length=64, null=True)),
                ('firearm_caliber', models.CharField(max_length=16, null=True)),
                ('weapon_description', models.CharField(max_length=64, null=True)),
                ('trr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trr.TRR')),
            ],
        ),
        migrations.CreateModel(
            name='TRRStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=16, null=True)),
                ('star', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(choices=[(b'SUBMITTED', b'SUBMITTED'), (b'REVIEWED', b'REVIEWED'), (b'APPROVED', b'APPROVED')], max_length=16, null=True)),
                ('status_datetime', models.DateTimeField(null=True)),
                ('age', models.SmallIntegerField(null=True)),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Officer')),
                ('trr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trr.TRR')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponDischarge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_type', models.CharField(max_length=32, null=True)),
                ('weapon_type_description', models.CharField(max_length=32, null=True)),
                ('firearm_make', models.CharField(max_length=64, null=True)),
                ('firearm_model', models.CharField(max_length=32, null=True)),
                ('firearm_barrel_length', models.CharField(max_length=16, null=True)),
                ('firearm_caliber', models.CharField(max_length=16, null=True)),
                ('total_number_of_shots', models.SmallIntegerField(null=True)),
                ('firearm_reloaded', models.NullBooleanField()),
                ('number_of_catdridge_reloaded', models.SmallIntegerField(null=True)),
                ('handgun_worn_type', models.CharField(choices=[(b'RIGHT SIDE (WAIST)', b'Right Side (Waist)'), (b'OTHER (SPECIFY)', b'Other (Specify)'), (b'LEFT SIDE (WAIST)', b'Left Side (Waist)')], max_length=32, null=True)),
                ('handgun_drawn_type', models.CharField(choices=[(b'STRONG SIDE DRAW', b'Strong Side Draw'), (b'CROSS DRAW', b'Cross Draw'), (b'OTHER (SPECIFY)', b'Other (Specify)')], max_length=32, null=True)),
                ('method_used_to_reload', models.CharField(max_length=64, null=True)),
                ('sight_used', models.NullBooleanField()),
                ('protective_cover_used', models.CharField(max_length=32, null=True)),
                ('discharge_distance', models.CharField(max_length=16, null=True)),
                ('object_struck_of_discharge', models.CharField(choices=[(b'OBJECT', b'OBJECT'), (b'PERSON', b'PERSON'), (b'UNKNOWN', b'UNKNOWN'), (b'BOTH', b'BOTH')], max_length=32, null=True)),
                ('discharge_position', models.CharField(choices=[(b'STANDING', b'Standing'), (b'SITTING', b'Sitting'), (b'OTHER (SPECIFY)', b'Other (Specify)'), (b'KNEELING', b'kneeling'), (b'LYING DOWN', b'Lying Down')], max_length=32, null=True)),
                ('trr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trr.TRR')),
            ],
        ),
    ]
