# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-14 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trr', '0003_add_tables_actionresponse_charge_subjectweapon_trrstatus_weapondischarge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapondischarge',
            name='discharge_position',
            field=models.CharField(choices=[(b'STANDING', b'Standing'), (b'SITTING', b'Sitting'), (b'OTHER (SPECIFY)', b'Other (Specify)'), (b'KNEELING', b'Kneeling'), (b'LYING DOWN', b'Lying Down')], max_length=32, null=True),
        ),
    ]
