# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-17 04:23
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_area_extra_fields'),
        ('trr', '0004_discharge_position_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trr',
            old_name='officer_duty_status',
            new_name='officer_on_duty',
        ),
        migrations.AddField(
            model_name='trr',
            name='officer_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.PoliceUnit'),
        ),
        migrations.AddField(
            model_name='trr',
            name='officer_unit_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trr_unit_detail_reverse', to='data.PoliceUnit'),
        ),
        migrations.AddField(
            model_name='trr',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='actionresponse',
            name='action_category',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='actionresponse',
            name='action_sub_category',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
