# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-06 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trr', '0011_import_weapondischarge_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRRAttachmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('trr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trr.TRR')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='trrattachmentrequest',
            unique_together=set([('trr', 'email')]),
        ),
    ]
