# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-01 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trr', '0012_trr_attachment_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='trrattachmentrequest',
            name='added_to_foia_airtable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trrattachmentrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
