# Generated by Django 2.1.3 on 2018-11-23 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trr', '0013_trrattachmentrequest_added_to_foia_airtable_and_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionresponse',
            name='person',
            field=models.CharField(choices=[('Member Action', 'Member Action'), ('Subject Action', 'Subject Action')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='actionresponse',
            name='resistance_level',
            field=models.CharField(choices=[('Active', 'Active'), ('Passive', 'Passive'), ('Assault/Battery', 'Assault/Battery'), ('Deadly Force', 'Deadly Force')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='actionresponse',
            name='resistance_type',
            field=models.CharField(choices=[('Active Resister', 'Active Resister'), ('Passive Resister', 'Passive Resister'), ('Assailant Battery', 'Assailant Battery'), ('Assailant Assault/Battery', 'Assailant Assault/Battery'), ('Assailant Assault', 'Assailant Assault'), ('Assailant Deadly Force', 'Assailant Deadly Force')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='trr',
            name='direction',
            field=models.CharField(choices=[('West', 'West'), ('North', 'North'), ('South', 'South'), ('East', 'East')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='trr',
            name='indoor_or_outdoor',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='trr',
            name='lighting_condition',
            field=models.CharField(choices=[('DAYLIGHT', 'Daylight'), ('GOOD ARTIFICIAL', 'Good Artificial'), ('DUSK', 'Dusk'), ('NIGHT', 'Night'), ('POOR ARTIFICIAL', 'Poor Artificial'), ('DAWN', 'Dawn')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='trr',
            name='officer_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.PoliceUnit'),
        ),
        migrations.AlterField(
            model_name='trr',
            name='officer_unit_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trr_unit_detail_reverse', to='data.PoliceUnit'),
        ),
        migrations.AlterField(
            model_name='trr',
            name='party_fired_first',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('OTHER', 'Other'), ('OFFENDER', 'Offender')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='trr',
            name='subject_gender',
            field=models.CharField(choices=[['M', 'Male'], ['F', 'Female'], ['X', 'X']], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='trr',
            name='weather_condition',
            field=models.CharField(choices=[('OTHER', 'Other'), ('CLEAR', 'Clear'), ('SNOW', 'Snow'), ('RAIN', 'Rain'), ('SLEET/HAIL', 'Sleet/hail'), ('SEVERE CROSS WIND', 'Severe Cross Wind'), ('FOG/SMOKE/HAZE', 'Fog/smoke/haze')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='trrstatus',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('REVIEWED', 'REVIEWED'), ('APPROVED', 'APPROVED')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='weapondischarge',
            name='discharge_position',
            field=models.CharField(choices=[('STANDING', 'Standing'), ('SITTING', 'Sitting'), ('OTHER (SPECIFY)', 'Other (Specify)'), ('KNEELING', 'Kneeling'), ('LYING DOWN', 'Lying Down')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='weapondischarge',
            name='handgun_drawn_type',
            field=models.CharField(choices=[('STRONG SIDE DRAW', 'Strong Side Draw'), ('CROSS DRAW', 'Cross Draw'), ('OTHER (SPECIFY)', 'Other (Specify)')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='weapondischarge',
            name='handgun_worn_type',
            field=models.CharField(choices=[('RIGHT SIDE (WAIST)', 'Right Side (Waist)'), ('OTHER (SPECIFY)', 'Other (Specify)'), ('LEFT SIDE (WAIST)', 'Left Side (Waist)')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='weapondischarge',
            name='object_struck_of_discharge',
            field=models.CharField(choices=[('OBJECT', 'OBJECT'), ('PERSON', 'PERSON'), ('UNKNOWN', 'UNKNOWN'), ('BOTH', 'BOTH')], max_length=32, null=True),
        ),
    ]
