# Generated by Django 2.1.3 on 2018-12-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trr', '0014_add_on_delete_to_foreign_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trrattachmentrequest',
            name='added_to_foia_airtable',
        ),
        migrations.AddField(
            model_name='trrattachmentrequest',
            name='airtable_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
