# Generated by Django 2.1.3 on 2018-12-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trr', '0015_attachment_request_add_airtable_record_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trrattachmentrequest',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
