# Generated by Django 2.2.10 on 2024-05-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trr', '0017_add_created_at_and_updated_at_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trr',
            name='officer_rank',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
