# Generated by Django 2.2.10 on 2024-06-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trr', '0018_auto_20240527_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectweapon',
            name='weapon_description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
