# Generated by Django 2.2.10 on 2024-06-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trr', '0019_auto_20240610_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapondischarge',
            name='weapon_type_description',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
