# Generated by Django 2.2.10 on 2024-06-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trr', '0020_auto_20240610_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapondischarge',
            name='weapon_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
